{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBStartErrorCode","text":"StartErrorCode"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/starterror\/startcode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError\/startCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StartErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBStartErrorCode"},{"kind":"text","text":"?"}],"title":"startCode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChartboostSDK10StartErrorC9startCodeAA0cdF0OSgvp","modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartError/startCode":{"role":"symbol","title":"startCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StartErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBStartErrorCode"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError\/startCode","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/starterror\/startcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode":{"role":"symbol","title":"StartErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed start operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartErrorCode"}],"url":"\/documentation\/chartboostsdk\/starterrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartError":{"role":"symbol","title":"StartError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartError"}],"abstract":[{"type":"text","text":"An error object passed on SDK start completion callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartError"}],"url":"\/documentation\/chartboostsdk\/starterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/title","value":"CHBStartErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartError\/title","value":"CHBStartError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartError\/fragments","value":[{"kind":"identifier","text":"CHBStartError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}