{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBCacheErrorCode","text":"CacheErrorCode"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/cacheerror\/cachecode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/cacheCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBCacheErrorCode"},{"kind":"text","text":"?"}],"title":"cacheCode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChartboostSDK10CacheErrorC9cacheCodeAA0cdF0OSgvp","modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError":{"role":"symbol","title":"CacheError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheError"}],"abstract":[{"type":"text","text":"An error object passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheError"}],"url":"\/documentation\/chartboostsdk\/cacheerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode":{"role":"symbol","title":"CacheErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed cache operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheErrorCode"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError/cacheCode":{"role":"symbol","title":"cacheCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBCacheErrorCode"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/cacheCode","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/cacheerror\/cachecode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/title","value":"CHBCacheError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/fragments","value":[{"kind":"identifier","text":"CHBCacheError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/title","value":"CHBCacheErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}