{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CHBCacheError) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/cacheerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/cacheerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSError"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSCoding","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSCopying","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSSecureCoding","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/s5ErrorP","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error object passed on cache-related delegate methods."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheError"}],"title":"CacheError","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChartboostSDK@objc(cs)CHBCacheError","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CacheError"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/cacheCode"]}],"references":{"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s5ErrorP"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSCoding"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError":{"role":"symbol","title":"CacheError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheError"}],"abstract":[{"type":"text","text":"An error object passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheError"}],"url":"\/documentation\/chartboostsdk\/cacheerror"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSSecureCoding"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSCopying"},"doc://com.chartboost.ChartboostSDK/objc(cs)NSError":{"type":"unresolvable","title":"NSError","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSError"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/chartboostsdk\/cacheerror\/initwithcoder:"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError/initWithDomain:code:userInfo:":{"role":"symbol","title":"initWithDomain:code:userInfo:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDomain:code:userInfo:"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/initWithDomain:code:userInfo:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDomain:code:userInfo:"}],"url":"\/documentation\/chartboostsdk\/cacheerror\/initwithdomain:code:userinfo:"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError/cacheCode":{"role":"symbol","title":"cacheCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBCacheErrorCode"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/cacheCode","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/cacheerror\/cachecode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CHBCacheError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCacheError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBCacheError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/initWithCoder:","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError\/initWithDomain:code:userInfo:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSError"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheError"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/title","value":"CHBCacheError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/fragments","value":[{"kind":"identifier","text":"CHBCacheError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}