{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CHBCacheErrorCode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/cacheerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/cacheerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes for failed cache operations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheErrorCode"}],"title":"CacheErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ChartboostSDK@E@CHBCacheErrorCode","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CacheErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/assetDownloadFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internalError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internetUnavailable","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/networkFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/noAdFound","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/publisherDisabled","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/serverError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/sessionNotStarted"]},{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/Equatable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/assetDownloadFailure":{"role":"symbol","title":"CacheErrorCode.assetDownloadFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"assetDownloadFailure"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/assetDownloadFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeAssetDownloadFailure"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/assetdownloadfailure"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/internetUnavailable":{"role":"symbol","title":"CacheErrorCode.internetUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internetUnavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeInternetUnavailable"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/internetunavailable"},"doc://com.chartboost.ChartboostSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SY"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/noAdFound":{"role":"symbol","title":"CacheErrorCode.noAdFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noAdFound"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/noAdFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeNoAdFound"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/noadfound"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/sessionNotStarted":{"role":"symbol","title":"CacheErrorCode.sessionNotStarted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionNotStarted"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/sessionNotStarted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeSessionNotStarted"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/sessionnotstarted"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/cacheerrorcode\/equatable-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode":{"role":"symbol","title":"CacheErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed cache operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheErrorCode"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/description","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/cacheerrorcode\/description"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/cacheerrorcode\/init(rawvalue:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/publisherDisabled":{"role":"symbol","title":"CacheErrorCode.publisherDisabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publisherDisabled"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/publisherDisabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodePublisherDisabled"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/publisherdisabled"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/networkFailure":{"role":"symbol","title":"CacheErrorCode.networkFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkFailure"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/networkFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeNetworkFailure"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/networkfailure"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/internalError":{"role":"symbol","title":"CacheErrorCode.internalError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeInternalError"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/internalerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/serverError":{"role":"symbol","title":"CacheErrorCode.serverError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/serverError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeServerError"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/servererror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/cacheerrorcode\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CHBCacheErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBCacheErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/assetDownloadFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internalError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internetUnavailable","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/networkFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/noAdFound","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/publisherDisabled","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/serverError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/sessionNotStarted"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1assetDownloadFailure\/title","value":"CHBCacheErrorCodeAssetDownloadFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1assetDownloadFailure\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeAssetDownloadFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1internetUnavailable\/title","value":"CHBCacheErrorCodeInternetUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1internetUnavailable\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeInternetUnavailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1noAdFound\/title","value":"CHBCacheErrorCodeNoAdFound"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1noAdFound\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeNoAdFound"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1sessionNotStarted\/title","value":"CHBCacheErrorCodeSessionNotStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1sessionNotStarted\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeSessionNotStarted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/title","value":"CHBCacheErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1publisherDisabled\/title","value":"CHBCacheErrorCodePublisherDisabled"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1publisherDisabled\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodePublisherDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1networkFailure\/title","value":"CHBCacheErrorCodeNetworkFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1networkFailure\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeNetworkFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1internalError\/title","value":"CHBCacheErrorCodeInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1internalError\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1serverError\/title","value":"CHBCacheErrorCodeServerError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1serverError\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeServerError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}