{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBLoggingLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/cblogginglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/cblogginglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/SY","doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chartboost SDK logging level options"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBLoggingLevel"}],"title":"CBLoggingLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@CBLoggingLevel","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevel"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/error","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/info","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/off","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/verbose","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/Equatable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/off":{"role":"symbol","title":"CBLoggingLevel.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/off","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevelOff"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel\/off"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/error":{"role":"symbol","title":"CBLoggingLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevelError"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel\/error"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel":{"role":"symbol","title":"CBLoggingLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBLoggingLevel"}],"abstract":[{"type":"text","text":"Chartboost SDK logging level options"}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevel"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/warning":{"role":"symbol","title":"CBLoggingLevel.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevelWarning"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel\/warning"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/info":{"role":"symbol","title":"CBLoggingLevel.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/info","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevelInfo"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel\/info"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/cblogginglevel\/rawrepresentable-implementations"},"doc://com.chartboost.ChartboostSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/cblogginglevel\/equatable-implementations"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SY"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/cblogginglevel\/init(rawvalue:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/verbose":{"role":"symbol","title":"CBLoggingLevel.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevelVerbose"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel\/verbose"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CBLoggingLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBLoggingLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/error","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/info","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/off","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/verbose","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/warning"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBLoggingLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1off\/title","value":"CBLoggingLevelOff"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1off\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevelOff"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1error\/title","value":"CBLoggingLevelError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1error\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel\/title","value":"CBLoggingLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1warning\/title","value":"CBLoggingLevelWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1warning\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevelWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1info\/title","value":"CBLoggingLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1info\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevelInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1verbose\/title","value":"CBLoggingLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevelVerbose"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}