{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Make sure to start Chartboost before requesting any ad."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Setting data use consent information beforehand is also highly recommended, otherwise Chartboost’s ability to provide ads might be hindered."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chartboost"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chartboost"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides global settings and shared functionality for the Chartboost SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"}],"title":"Chartboost","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)Chartboost","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Chartboost"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/addDataUseConsent(_:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/bidderToken()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/clearDataUseConsent(for:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/dataUseConsent(for:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/getSDKVersion()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/setLoggingLevel(_:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/start(withAppID:appSignature:completion:)"]}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/bidderToken()":{"role":"symbol","title":"bidderToken()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bidderToken"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the token used to authenticate with the Chartboost servers."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/bidderToken()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bidderToken"}],"url":"\/documentation\/chartboostsdk\/chartboost\/biddertoken()"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/dataUseConsent(for:)":{"role":"symbol","title":"dataUseConsent(for:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataUseConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the current consent status for the desired privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/dataUseConsent(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataUseConsentForPrivacyStandard:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/datauseconsent(for:)"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/clearDataUseConsent(for:)":{"role":"symbol","title":"clearDataUseConsent(for:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearDataUseConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Clears the previously added consent for the desired privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/clearDataUseConsent(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearDataUseConsentForPrivacyStandard:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/cleardatauseconsent(for:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/start(withAppID:appSignature:completion:)":{"role":"symbol","title":"start(withAppID:appSignature:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StartError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBStartError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the SDK with the publisher app credentials."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/start(withAppID:appSignature:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppID:appSignature:completion:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/start(withappid:appsignature:completion:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/addDataUseConsent(_:)":{"role":"symbol","title":"addDataUseConsent(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataUseConsent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use to restrict Chartboost’s ability to collect personal data from the user."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/addDataUseConsent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addDataUseConsent:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/adddatauseconsent(_:)"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/setLoggingLevel(_:)":{"role":"symbol","title":"setLoggingLevel(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoggingLevel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CBLoggingLevel","preciseIdentifier":"c:@E@CBLoggingLevel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets a logging level."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/setLoggingLevel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLoggingLevel:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/setlogginglevel(_:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost":{"role":"symbol","title":"Chartboost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"}],"abstract":[{"type":"text","text":"Provides global settings and shared functionality for the Chartboost SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chartboost"}],"url":"\/documentation\/chartboostsdk\/chartboost"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"},"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/getSDKVersion()":{"role":"symbol","title":"getSDKVersion()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSDKVersion"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The version of the Chartboost SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/getSDKVersion()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSDKVersion"}],"url":"\/documentation\/chartboostsdk\/chartboost\/getsdkversion()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Chartboost"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Chartboost"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Chartboost"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/addDataUseConsent(_:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/bidderToken()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/clearDataUseConsent(for:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/dataUseConsent(for:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/getSDKVersion()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/setLoggingLevel(_:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/start(withAppID:appSignature:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1bidderToken()\/title","value":"bidderToken"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1bidderToken()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bidderToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1dataUseConsent(for:)\/title","value":"dataUseConsentForPrivacyStandard:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1dataUseConsent(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"dataUseConsentForPrivacyStandard:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1clearDataUseConsent(for:)\/title","value":"clearDataUseConsentForPrivacyStandard:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1clearDataUseConsent(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"clearDataUseConsentForPrivacyStandard:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1start(withAppID:appSignature:completion:)\/title","value":"startWithAppID:appSignature:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1start(withAppID:appSignature:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppID:appSignature:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1addDataUseConsent(_:)\/title","value":"addDataUseConsent:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1addDataUseConsent(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addDataUseConsent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1setLoggingLevel(_:)\/title","value":"setLoggingLevel:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1setLoggingLevel(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLoggingLevel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/title","value":"Chartboost"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/fragments","value":[{"kind":"identifier","text":"Chartboost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1getSDKVersion()\/title","value":"getSDKVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1getSDKVersion()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSDKVersion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}