{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdEvent"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the SDK exists various types of CHBAdEvent are related to the Ad Delegate callbacks."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CHBCacheEvent"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CHBShowEvent"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CHBImpressionEvent"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CHBClickEvent"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CHBDismissEvent"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CHBRewardEvent"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbadevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbadevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBImpressionEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CHBAdEvent is a NSObject subclass, it contains information about a specific event and is related to an ad."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdEvent"}],"title":"CHBAdEvent","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)CHBAdEvent","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBAdEvent"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent\/ad","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent\/adID"]}],"references":{"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdEvent":{"role":"symbol","title":"CHBAdEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdEvent"}],"abstract":[{"type":"text","text":"CHBAdEvent is a NSObject subclass, it contains information about a specific event and is related to an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdEvent"}],"url":"\/documentation\/chartboostsdk\/chbadevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewardEvent":{"role":"symbol","title":"CHBRewardEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewardEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on reward-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewardEvent"}],"url":"\/documentation\/chartboostsdk\/chbrewardevent"},"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBCacheEvent":{"role":"symbol","title":"CHBCacheEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheEvent"}],"url":"\/documentation\/chartboostsdk\/chbcacheevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDismissEvent":{"role":"symbol","title":"CHBDismissEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDismissEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on dismiss-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDismissEvent"}],"url":"\/documentation\/chartboostsdk\/chbdismissevent"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdEvent/adID":{"role":"symbol","title":"adID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A string that uniquely identifies the cached ad, updated when a cache operation ends."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent\/adID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adID"}],"url":"\/documentation\/chartboostsdk\/chbadevent\/adid"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBShowEvent":{"role":"symbol","title":"CHBShowEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBShowEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on show-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowEvent"}],"url":"\/documentation\/chartboostsdk\/chbshowevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBImpressionEvent":{"role":"symbol","title":"CHBImpressionEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBImpressionEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on impression-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBImpressionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBImpressionEvent"}],"url":"\/documentation\/chartboostsdk\/chbimpressionevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBClickEvent":{"role":"symbol","title":"CHBClickEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBClickEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickEvent"}],"url":"\/documentation\/chartboostsdk\/chbclickevent"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdEvent/ad":{"role":"symbol","title":"ad","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBAd","preciseIdentifier":"c:objc(pl)CHBAd"}],"abstract":[{"type":"text","text":"The ad related to the event."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent\/ad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ad"}],"url":"\/documentation\/chartboostsdk\/chbadevent\/ad"},"doc://com.chartboost.ChartboostSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CHBAdEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBAdEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBAdEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent\/ad","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent\/adID"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBImpressionEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdEvent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent\/title","value":"CHBAdEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent\/fragments","value":[{"kind":"identifier","text":"CHBAdEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardEvent\/title","value":"CHBRewardEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardEvent\/fragments","value":[{"kind":"identifier","text":"CHBRewardEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/title","value":"CHBCacheEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/fragments","value":[{"kind":"identifier","text":"CHBCacheEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissEvent\/title","value":"CHBDismissEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissEvent\/fragments","value":[{"kind":"identifier","text":"CHBDismissEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent~1adID\/title","value":"adID"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent~1adID\/fragments","value":[{"kind":"identifier","text":"adID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBShowEvent\/title","value":"CHBShowEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBShowEvent\/fragments","value":[{"kind":"identifier","text":"CHBShowEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBImpressionEvent\/title","value":"CHBImpressionEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBImpressionEvent\/fragments","value":[{"kind":"identifier","text":"CHBImpressionEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/title","value":"CHBClickEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/fragments","value":[{"kind":"identifier","text":"CHBClickEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent~1ad\/title","value":"ad"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent~1ad\/fragments","value":[{"kind":"identifier","text":"ad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}