{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Provides methods to receive notifications related to an ad’s actions and to control its behavior."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbaddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitialDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The protocol which all Chartboost ad delegates inherit from."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"}],"title":"CHBAdDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)CHBAdDelegate","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBAdDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didCacheAd(_:error:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didClickAd(_:error:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didRecordImpression(_:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didShowAd(_:error:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/willShowAd(_:)"]}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitialDelegate":{"role":"symbol","title":"CHBInterstitialDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitialDelegate"}],"abstract":[{"type":"text","text":"Interstitial delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitialDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBInterstitialDelegate"}],"url":"\/documentation\/chartboostsdk\/chbinterstitialdelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDismissableAdDelegate":{"role":"symbol","title":"CHBDismissableAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDismissableAdDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for ads that can be dismissed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDismissableAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbdismissableaddelegate"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerDelegate":{"role":"symbol","title":"CHBBannerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerDelegate"}],"abstract":[{"type":"text","text":"Banner delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerDelegate"}],"url":"\/documentation\/chartboostsdk\/chbbannerdelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate":{"role":"symbol","title":"CHBAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"}],"abstract":[{"type":"text","text":"The protocol which all Chartboost ad delegates inherit from."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/willShowAd(_:)":{"role":"symbol","title":"willShowAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willShowAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBShowEvent","preciseIdentifier":"c:objc(cs)CHBShowEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called after a showFromViewController: call, right before an ad is presented."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/willShowAd(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willShowAd:"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate\/willshowad(_:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/didClickAd(_:error:)":{"navigatorTitle":[{"kind":"identifier","text":"didClickAd:error:"}],"role":"symbol","title":"didClickAd(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClickAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called after an ad has been clicked."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didClickAd(_:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostsdk\/chbaddelegate\/didclickad(_:error:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/didRecordImpression(_:)":{"role":"symbol","title":"didRecordImpression(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRecordImpression"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBImpressionEvent","preciseIdentifier":"c:objc(cs)CHBImpressionEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called after an ad has recorded an impression."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didRecordImpression(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didRecordImpression:"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate\/didrecordimpression(_:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/didCacheAd(_:error:)":{"navigatorTitle":[{"kind":"identifier","text":"didCacheAd:error:"}],"role":"symbol","title":"didCacheAd(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCacheAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBCacheEvent","preciseIdentifier":"c:objc(cs)CHBCacheEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBCacheError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called after a cache call, either if an ad has been loaded from the Chartboost servers and cached, or tried to but failed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didCacheAd(_:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostsdk\/chbaddelegate\/didcachead(_:error:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewardedDelegate":{"role":"symbol","title":"CHBRewardedDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewardedDelegate"}],"abstract":[{"type":"text","text":"Rewarded delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewardedDelegate"}],"url":"\/documentation\/chartboostsdk\/chbrewardeddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/didShowAd(_:error:)":{"role":"symbol","title":"didShowAd(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didShowAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBShowEvent","preciseIdentifier":"c:objc(cs)CHBShowEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShowError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBShowError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called after a showFromViewController: call, either if the ad has been presented and an ad impression logged, or if the operation failed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didShowAd(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didShowAd:error:"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate\/didshowad(_:error:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CHBAdDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBAdDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBAdDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didCacheAd(_:error:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didClickAd(_:error:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didRecordImpression(_:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didShowAd(_:error:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/willShowAd(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitialDelegate\/title","value":"CHBInterstitialDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitialDelegate\/fragments","value":[{"kind":"identifier","text":"CHBInterstitialDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate\/title","value":"CHBDismissableAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBDismissableAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/title","value":"CHBBannerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/fragments","value":[{"kind":"identifier","text":"CHBBannerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/title","value":"CHBAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1willShowAd(_:)\/title","value":"willShowAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1willShowAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willShowAd:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didClickAd(_:error:)\/title","value":"didClickAd:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didClickAd(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didClickAd:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didRecordImpression(_:)\/title","value":"didRecordImpression:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didRecordImpression(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didRecordImpression:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didCacheAd(_:error:)\/title","value":"didCacheAd:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didCacheAd(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCacheAd:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/title","value":"CHBRewardedDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/fragments","value":[{"kind":"identifier","text":"CHBRewardedDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didShowAd(_:error:)\/title","value":"didShowAd:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didShowAd(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didShowAd:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}