{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSizeStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize","text":"CHBBannerSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbbannersizestandard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbbannersizestandard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeStandard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"“Banner” - Standard banner size on phones."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSizeStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"}],"title":"CHBBannerSizeStandard","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@CHBBannerSizeStandard","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBBannerSizeStandard"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerSizeStandard":{"role":"symbol","title":"CHBBannerSizeStandard","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSizeStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"}],"abstract":[{"type":"text","text":"“Banner” - Standard banner size on phones."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerSizeStandard"}],"url":"\/documentation\/chartboostsdk\/chbbannersizestandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerSize":{"role":"symbol","title":"CHBBannerSize","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSize"}],"abstract":[{"type":"text","text":"Defines standard sizes for CHBBanner objects."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerSize"}],"url":"\/documentation\/chartboostsdk\/chbbannersize"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"CHBBannerSizeStandard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBBannerSizeStandard"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize","text":"CHBBannerSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSizeStandard"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeStandard\/title","value":"CHBBannerSizeStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeStandard\/fragments","value":[{"kind":"identifier","text":"CHBBannerSizeStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSize\/title","value":"CHBBannerSize"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSize\/fragments","value":[{"kind":"identifier","text":"CHBBannerSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}