{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A banner ad has a CHBBannerSize which corresponds to the view’s intrinsicContentSize."},{"type":"text","text":" "},{"type":"text","text":"The developer should not give the banner view object a frame size different than its CHBBannerSize property."},{"type":"text","text":" "},{"type":"text","text":"If you are using AutoLayout just give the banner an X and Y position constraint and it will be automatically sized."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create and present as many banners as you want at the same time."},{"type":"text","text":" "},{"type":"text","text":"For more information on integrating and using the Chartboost SDK please visit our help site documentation at "},{"type":"reference","isActive":true,"identifier":"https:\/\/help.chartboost.com"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A typical implementation would look like this:"}]},{"type":"codeListing","syntax":"objc","code":["- (void)createAndShowBanner {","   CHBBanner *banner = [[CHBBanner alloc] initWithSize:CHBBannerSizeStandard location:@\"YOUR_LOCATION_NAME\" delegate:self];","   banner.translatesAutoresizingMaskIntoConstraints = NO;","   [self.view addSubview:banner];","   [NSLayoutConstraint activateConstraints:@[[banner.bottomAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.bottomAnchor],","                                            [banner.centerXAnchor constraintEqualToAnchor:self.view.centerXAnchor]]];","   [banner showFromViewController:self];","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbbanner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbbanner"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSCoding","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)CALayerDelegate","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIAppearance","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIDynamicItem","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIFocusItem","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CHBBanner is a UIView subclass able to show banner ads. Once obtained via the provided initializer, the"},{"type":"text","text":" "},{"type":"text","text":"developer is responsible of adding it to the app’s view hierarchy and laying it out properly."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"}],"title":"CHBBanner","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)CHBBanner","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBBanner"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:delegate:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:mediation:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/delegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/isCached","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/location","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache(bidResponse:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/clearCache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/show(from:)"]}],"references":{"doc://com.chartboost.ChartboostSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSCoding"},"doc://com.chartboost.ChartboostSDK/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)UIView"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIAccessibilityIdentification"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/init(size:location:mediation:delegate:)":{"role":"symbol","title":"init(size:location:mediation:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBMediation","preciseIdentifier":"c:objc(cs)CHBMediation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerDelegate","preciseIdentifier":"c:objc(pl)CHBBannerDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The initializer for banner ads intended to be mediated by another SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:mediation:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSize:location:mediation:delegate:"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/init(size:location:mediation:delegate:)"},"https://help.chartboost.com":{"title":"Chartboost Helpsite","titleInlineContent":[{"type":"text","text":"Chartboost Helpsite"}],"type":"link","identifier":"https:\/\/help.chartboost.com","url":"https:\/\/help.chartboost.com"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIAppearanceContainer"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/cache()":{"role":"symbol","title":"cache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Caches an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cache"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/cache()"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIAppearance"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UICoordinateSpace"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/init(size:location:delegate:)":{"role":"symbol","title":"init(size:location:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerDelegate","preciseIdentifier":"c:objc(pl)CHBBannerDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The initializer for the banner object. Default UIView initializers should not be used!"}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSize:location:delegate:"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/init(size:location:delegate:)"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIFocusItem"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/show(from:)":{"role":"symbol","title":"show(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/show(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showFromViewController:"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/show(from:)"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.chartboost.ChartboostSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIDynamicItem"},"doc://com.chartboost.ChartboostSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UILargeContentViewerItem"},"doc://com.chartboost.ChartboostSDK/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)CALayerDelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/cache(bidResponse:)":{"role":"symbol","title":"cache(bidResponse:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bidResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Caches an ad using an OpenRTB bid response."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache(bidResponse:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cacheBidResponse:"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/cache(bidresponse:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"}],"abstract":[{"type":"text","text":"Size for the banner ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/size"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/location":{"role":"symbol","title":"location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Chartboost location for the ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"location"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/location"},"doc://com.chartboost.ChartboostSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UITraitEnvironment"},"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/clearCache()":{"role":"symbol","title":"clearCache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clears the ad cache."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/clearCache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/clearcache()"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIFocusEnvironment"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner":{"role":"symbol","title":"CHBBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"}],"abstract":[{"type":"text","text":"CHBBanner is a UIView subclass able to show banner ads. Once obtained via the provided initializer, the"},{"type":"text","text":" "},{"type":"text","text":"developer is responsible of adding it to the app’s view hierarchy and laying it out properly."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBanner"}],"url":"\/documentation\/chartboostsdk\/chbbanner"},"doc://com.chartboost.ChartboostSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)UIFocusItemContainer"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerDelegate","preciseIdentifier":"c:objc(pl)CHBBannerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate instance to receive banner callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/delegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAd":{"role":"symbol","title":"CHBAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAd"}],"abstract":[{"type":"text","text":"The protocol to which all Chartboost ads conform to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAd"}],"url":"\/documentation\/chartboostsdk\/chbad"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/isCached":{"role":"symbol","title":"isCached","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines if a cached ad exists."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/isCached","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCached"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/iscached"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CHBBanner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBBanner"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBBanner"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/delegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/isCached","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/location","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache(bidResponse:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/clearCache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:delegate:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:mediation:delegate:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/show(from:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1init(size:location:mediation:delegate:)\/title","value":"initWithSize:location:mediation:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1init(size:location:mediation:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSize:location:mediation:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1cache()\/title","value":"cache"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1cache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1init(size:location:delegate:)\/title","value":"initWithSize:location:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1init(size:location:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSize:location:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1show(from:)\/title","value":"showFromViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1show(from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showFromViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1cache(bidResponse:)\/title","value":"cacheBidResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1cache(bidResponse:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheBidResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1location\/title","value":"location"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1location\/fragments","value":[{"kind":"identifier","text":"location"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1clearCache()\/title","value":"clearCache"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1clearCache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/title","value":"CHBBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/fragments","value":[{"kind":"identifier","text":"CHBBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/title","value":"CHBAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/fragments","value":[{"kind":"identifier","text":"CHBAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1isCached\/title","value":"isCached"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1isCached\/fragments","value":[{"kind":"identifier","text":"isCached"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}