{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbcacheevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbcacheevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on cache-related delegate methods."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheEvent"}],"title":"CHBCacheEvent","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)CHBCacheEvent","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBCacheEvent"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"references":{"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBCacheEvent":{"role":"symbol","title":"CHBCacheEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheEvent"}],"url":"\/documentation\/chartboostsdk\/chbcacheevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdEvent":{"role":"symbol","title":"CHBAdEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdEvent"}],"abstract":[{"type":"text","text":"CHBAdEvent is a NSObject subclass, it contains information about a specific event and is related to an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdEvent"}],"url":"\/documentation\/chartboostsdk\/chbadevent"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CHBCacheEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCacheEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBCacheEvent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheEvent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent","preciseIdentifier":"c:objc(cs)CHBAdEvent","text":"CHBAdEvent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/title","value":"CHBCacheEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/fragments","value":[{"kind":"identifier","text":"CHBCacheEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent\/title","value":"CHBAdEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent\/fragments","value":[{"kind":"identifier","text":"CHBAdEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}