{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitial"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To show an interstitial it first needs to be cached. Trying to show an uncached interstitial will always fail, thus it is recommended to always check if the ad is cached first."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can create and cache as many interstitial ads as you want, but only one can be presented at the same time."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information on integrating and using the Chartboost SDK please visit our help site documentation at "},{"type":"reference","isActive":true,"identifier":"https:\/\/help.chartboost.com"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A basic implementation would look like this:"}]},{"type":"codeListing","syntax":"objc","code":["- (void)createAndCacheInterstitial {","   self.interstitial = [[CHBInterstitial alloc] initWithLocation:@\"YOUR_LOCATION_NAME\" delegate:self];","   [self.interstitial cache];","}"," ","- (void)showInterstitial {","   if (self.interstitial.isCached) {","   [self.interstitial showFromViewController:self];","  }","}"," ","\/\/ Delegate methods","- (void)didCacheAd:(CHBCacheEvent *)event error:(nullable CHBCacheError *)error {","   if (error) {","     \/\/ Handle error, possibly scheduling a retry","   }","}"," ","- (void)willShowAd:(CHBShowEvent *)event {","   \/\/ Pause ongoing processes"," }"," ","- (void)didShowAd:(CHBShowEvent *)event error:(CHBShowError *)error {","   if (error) {","    \/\/ Resume paused processes","  }","}"," ","- (void)didDismissAd:(CHBDismissEvent *)event {","   \/\/ Resume paused processes","}"]},{"anchor":"Notes","level":1,"type":"heading","text":"Notes"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your application uses a View controller-based status bar appearance (usually the default), an ad shown with a valid view controller will hide the status bar. Otherwise it is your responsibility to hide it or not."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbinterstitial"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbinterstitial"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CHBInterstitial is a full-screen ad."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitial"}],"title":"CHBInterstitial","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)CHBInterstitial","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBInterstitial"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/init(location:delegate:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/init(location:mediation:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/delegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/isCached","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/location"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/cache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/cache(bidResponse:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/clearCache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/show(from:)"]}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/cache()":{"role":"symbol","title":"cache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Caches an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/cache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cache"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/cache()"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/isCached":{"role":"symbol","title":"isCached","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Determines if a cached ad exists."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/isCached","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCached"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/iscached"},"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAd":{"role":"symbol","title":"CHBAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAd"}],"abstract":[{"type":"text","text":"The protocol to which all Chartboost ads conform to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAd"}],"url":"\/documentation\/chartboostsdk\/chbad"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBInterstitialDelegate","preciseIdentifier":"c:objc(pl)CHBInterstitialDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate instance to receive interstitial callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/delegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/show(from:)":{"role":"symbol","title":"show(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/show(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showFromViewController:"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/show(from:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/cache(bidResponse:)":{"role":"symbol","title":"cache(bidResponse:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bidResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Caches an ad using an OpenRTB bid response."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/cache(bidResponse:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cacheBidResponse:"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/cache(bidresponse:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/clearCache()":{"role":"symbol","title":"clearCache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clears the ad cache."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/clearCache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/clearcache()"},"https://help.chartboost.com":{"title":"Chartboost Helpsite","titleInlineContent":[{"type":"text","text":"Chartboost Helpsite"}],"type":"link","identifier":"https:\/\/help.chartboost.com","url":"https:\/\/help.chartboost.com"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/init(location:delegate:)":{"role":"symbol","title":"init(location:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBInterstitialDelegate","preciseIdentifier":"c:objc(pl)CHBInterstitialDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The initializer for the interstitial object."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/init(location:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLocation:delegate:"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/init(location:delegate:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/init(location:mediation:delegate:)":{"role":"symbol","title":"init(location:mediation:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBMediation","preciseIdentifier":"c:objc(cs)CHBMediation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBInterstitialDelegate","preciseIdentifier":"c:objc(pl)CHBInterstitialDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The initializer for interstitial ads intended to be mediated by another SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/init(location:mediation:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLocation:mediation:delegate:"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/init(location:mediation:delegate:)"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial":{"role":"symbol","title":"CHBInterstitial","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitial"}],"abstract":[{"type":"text","text":"CHBInterstitial is a full-screen ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBInterstitial"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial"},"doc://com.chartboost.ChartboostSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/location":{"role":"symbol","title":"location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Chartboost location for the ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/location","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"location"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/location"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CHBInterstitial"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBInterstitial"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBInterstitial"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/delegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/isCached","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/location"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/cache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/cache(bidResponse:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/clearCache()","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/init(location:delegate:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/init(location:mediation:delegate:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/show(from:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitial"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1cache()\/title","value":"cache"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1cache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1isCached\/title","value":"isCached"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1isCached\/fragments","value":[{"kind":"identifier","text":"isCached"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/title","value":"CHBAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/fragments","value":[{"kind":"identifier","text":"CHBAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1show(from:)\/title","value":"showFromViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1show(from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showFromViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1cache(bidResponse:)\/title","value":"cacheBidResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1cache(bidResponse:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheBidResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1clearCache()\/title","value":"clearCache"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1clearCache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1init(location:delegate:)\/title","value":"initWithLocation:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1init(location:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocation:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1init(location:mediation:delegate:)\/title","value":"initWithLocation:mediation:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1init(location:mediation:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocation:mediation:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial\/title","value":"CHBInterstitial"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial\/fragments","value":[{"kind":"identifier","text":"CHBInterstitial"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1location\/title","value":"location"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1location\/fragments","value":[{"kind":"identifier","text":"location"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}