{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbprivacystandard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbprivacystandard"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/SY","doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Constant that identifies a privacy standard to comply to."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"title":"CHBPrivacyStandard","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandard"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/init(_:)","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/CCPA","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/COPPA","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/GDPR","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/LGPD"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/Equatable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/RawRepresentable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/_SwiftNewtypeWrapper-Implementations"],"generated":true}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/chbprivacystandard\/equatable-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/chbprivacystandard\/rawrepresentable-implementations"},"doc://com.chartboost.ChartboostSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/CCPA":{"role":"symbol","title":"CCPA","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/CCPA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandardCCPA"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard\/ccpa"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/COPPA":{"role":"symbol","title":"COPPA","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"COPPA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/COPPA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandardCOPPA"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard\/coppa"},"doc://com.chartboost.ChartboostSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SY"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/init(_:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/chbprivacystandard\/init(_:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/LGPD":{"role":"symbol","title":"LGPD","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"LGPD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/LGPD","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandardLGPD"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard\/lgpd"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard":{"role":"symbol","title":"CHBPrivacyStandard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"abstract":[{"type":"text","text":"Constant that identifies a privacy standard to comply to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandard"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/_SwiftNewtypeWrapper-Implementations":{"role":"collectionGroup","title":"_SwiftNewtypeWrapper Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/_SwiftNewtypeWrapper-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/chbprivacystandard\/_swiftnewtypewrapper-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/chbprivacystandard\/init(rawvalue:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/GDPR":{"role":"symbol","title":"GDPR","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/GDPR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandardGDPR"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard\/gdpr"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"CHBPrivacyStandard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandard"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBPrivacyStandard"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/CCPA","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/COPPA","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/GDPR","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/LGPD"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1CCPA\/title","value":"CHBPrivacyStandardCCPA"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1CCPA\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandardCCPA"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1COPPA\/title","value":"CHBPrivacyStandardCOPPA"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1COPPA\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandardCOPPA"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1LGPD\/title","value":"CHBPrivacyStandardLGPD"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1LGPD\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandardLGPD"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/title","value":"CHBPrivacyStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1GDPR\/title","value":"CHBPrivacyStandardGDPR"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1GDPR\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandardGDPR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}