{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CHBClickErrorCode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/clickerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/clickerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes for failed click operations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickErrorCode"}],"title":"ClickErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ChartboostSDK@E@CHBClickErrorCode","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ClickErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/internalError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriInvalid","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriUnrecognized"]},{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/Equatable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/clickerrorcode\/equatable-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/internalError":{"role":"symbol","title":"ClickErrorCode.internalError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/internalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickErrorCodeInternalError"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode\/internalerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/description","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/clickerrorcode\/description"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/clickerrorcode\/rawrepresentable-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode":{"role":"symbol","title":"ClickErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed click operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickErrorCode"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/clickerrorcode\/init(rawvalue:)"},"doc://com.chartboost.ChartboostSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SY"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/uriInvalid":{"role":"symbol","title":"ClickErrorCode.uriInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriInvalid"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriInvalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickErrorCodeUriInvalid"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode\/uriinvalid"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/uriUnrecognized":{"role":"symbol","title":"ClickErrorCode.uriUnrecognized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriUnrecognized"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriUnrecognized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickErrorCodeUriUnrecognized"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode\/uriunrecognized"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CHBClickErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBClickErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/internalError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriInvalid","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriUnrecognized"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBClickErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1internalError\/title","value":"CHBClickErrorCodeInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1internalError\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCodeInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/title","value":"CHBClickErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriInvalid\/title","value":"CHBClickErrorCodeUriInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriInvalid\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCodeUriInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriUnrecognized\/title","value":"CHBClickErrorCodeUriUnrecognized"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriUnrecognized\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCodeUriUnrecognized"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}