{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CHBShowErrorCode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/showerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/showerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes for failed show operations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorCode"}],"title":"ShowErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ChartboostSDK@E@CHBShowErrorCode","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ShowErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/assetsFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internalError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internetUnavailable","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noAdInstance","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noCachedAd","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noViewController","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/presentationFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/sessionNotStarted"]},{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/Equatable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/presentationFailure":{"role":"symbol","title":"ShowErrorCode.presentationFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationFailure"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/presentationFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodePresentationFailure"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/presentationfailure"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/noCachedAd":{"role":"symbol","title":"ShowErrorCode.noCachedAd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCachedAd"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noCachedAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeNoCachedAd"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/nocachedad"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/description","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/showerrorcode\/description"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode":{"role":"symbol","title":"ShowErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed show operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorCode"}],"url":"\/documentation\/chartboostsdk\/showerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/sessionNotStarted":{"role":"symbol","title":"ShowErrorCode.sessionNotStarted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionNotStarted"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/sessionNotStarted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeSessionNotStarted"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/sessionnotstarted"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/showerrorcode\/rawrepresentable-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/internetUnavailable":{"role":"symbol","title":"ShowErrorCode.internetUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internetUnavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeInternetUnavailable"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/internetunavailable"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/showerrorcode\/init(rawvalue:)"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SY"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/internalError":{"role":"symbol","title":"ShowErrorCode.internalError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeInternalError"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/internalerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/noViewController":{"role":"symbol","title":"ShowErrorCode.noViewController","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noViewController"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeNoViewController"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/noviewcontroller"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/noAdInstance":{"role":"symbol","title":"ShowErrorCode.noAdInstance","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noAdInstance"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noAdInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeNoAdInstance"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/noadinstance"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/showerrorcode\/equatable-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/assetsFailure":{"role":"symbol","title":"ShowErrorCode.assetsFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"assetsFailure"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/assetsFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeAssetsFailure"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/assetsfailure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CHBShowErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBShowErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/assetsFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internalError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internetUnavailable","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noAdInstance","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noCachedAd","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/noViewController","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/presentationFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/sessionNotStarted"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBShowErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1presentationFailure\/title","value":"CHBShowErrorCodePresentationFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1presentationFailure\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodePresentationFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1noCachedAd\/title","value":"CHBShowErrorCodeNoCachedAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1noCachedAd\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeNoCachedAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/title","value":"CHBShowErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1sessionNotStarted\/title","value":"CHBShowErrorCodeSessionNotStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1sessionNotStarted\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeSessionNotStarted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1internetUnavailable\/title","value":"CHBShowErrorCodeInternetUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1internetUnavailable\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeInternetUnavailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1internalError\/title","value":"CHBShowErrorCodeInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1internalError\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1noViewController\/title","value":"CHBShowErrorCodeNoViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1noViewController\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeNoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1noAdInstance\/title","value":"CHBShowErrorCodeNoAdInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1noAdInstance\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeNoAdInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1assetsFailure\/title","value":"CHBShowErrorCodeAssetsFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1assetsFailure\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeAssetsFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}