{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CHBStartErrorCode) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/starterrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/starterrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes for failed start operations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartErrorCode"}],"title":"StartErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ChartboostSDK@E@CHBStartErrorCode","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"StartErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/invalidCredentials","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/networkFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/serverError"]},{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/Equatable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/description","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/starterrorcode\/description"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/invalidCredentials":{"role":"symbol","title":"StartErrorCode.invalidCredentials","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCredentials"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/invalidCredentials","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBStartErrorCodeInvalidCredentials"}],"url":"\/documentation\/chartboostsdk\/starterrorcode\/invalidcredentials"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/starterrorcode\/rawrepresentable-implementations"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/starterrorcode\/init(rawvalue:)"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/networkFailure":{"role":"symbol","title":"StartErrorCode.networkFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkFailure"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/networkFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBStartErrorCodeNetworkFailure"}],"url":"\/documentation\/chartboostsdk\/starterrorcode\/networkfailure"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/starterrorcode\/equatable-implementations"},"doc://com.chartboost.ChartboostSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SY"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/serverError":{"role":"symbol","title":"StartErrorCode.serverError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/serverError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBStartErrorCodeServerError"}],"url":"\/documentation\/chartboostsdk\/starterrorcode\/servererror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode":{"role":"symbol","title":"StartErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed start operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartErrorCode"}],"url":"\/documentation\/chartboostsdk\/starterrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CHBStartErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBStartErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/invalidCredentials","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/networkFailure","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/serverError"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBStartErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1invalidCredentials\/title","value":"CHBStartErrorCodeInvalidCredentials"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1invalidCredentials\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCodeInvalidCredentials"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1networkFailure\/title","value":"CHBStartErrorCodeNetworkFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1networkFailure\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCodeNetworkFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1serverError\/title","value":"CHBStartErrorCodeServerError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1serverError\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCodeServerError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/title","value":"CHBStartErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}