{"variants":[{"paths":["\/documentation\/chartboostsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBImpressionEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdEvents","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdSession","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdSessionConfiguration","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdSessionContext","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostMediaEvents","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostPartner","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostScriptInjector","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostVerificationScriptResource","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError"]},{"title":"Protocols","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitialDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate"]},{"title":"Structures","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard"]},{"title":"Variables","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeLeaderboard","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeMedium","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeStandard","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ChartboostVersionNumber"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/RedirectionURLFinished"]},{"title":"Enumerations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDCreativeType","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDFriendlyObstructionType","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDImpressionType","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDInteractionType","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDOwner","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDPlayerState","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"ChartboostSDK","title":"ChartboostSDK","symbolKind":"module","role":"collection","modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDFriendlyObstructionType":{"role":"symbol","title":"OMIDFriendlyObstructionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDFriendlyObstructionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"url":"\/documentation\/chartboostsdk\/omidfriendlyobstructiontype"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartError":{"role":"symbol","title":"StartError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartError"}],"abstract":[{"type":"text","text":"An error object passed on SDK start completion callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartError"}],"url":"\/documentation\/chartboostsdk\/starterror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner":{"role":"symbol","title":"CHBBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"}],"abstract":[{"type":"text","text":"CHBBanner is a UIView subclass able to show banner ads. Once obtained via the provided initializer, the"},{"type":"text","text":" "},{"type":"text","text":"developer is responsible of adding it to the app’s view hierarchy and laying it out properly."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBanner"}],"url":"\/documentation\/chartboostsdk\/chbbanner"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel":{"role":"symbol","title":"CBLoggingLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBLoggingLevel"}],"abstract":[{"type":"text","text":"Chartboost SDK logging level options"}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevel"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBImpressionEvent":{"role":"symbol","title":"CHBImpressionEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBImpressionEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on impression-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBImpressionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBImpressionEvent"}],"url":"\/documentation\/chartboostsdk\/chbimpressionevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowError":{"role":"symbol","title":"ShowError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowError"}],"abstract":[{"type":"text","text":"An error object passed on show-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowError"}],"url":"\/documentation\/chartboostsdk\/showerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBCacheEvent":{"role":"symbol","title":"CHBCacheEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheEvent"}],"url":"\/documentation\/chartboostsdk\/chbcacheevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBMediation":{"role":"symbol","title":"CHBMediation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBMediation"}],"abstract":[{"type":"text","text":"A class that holds information about the mediation library used to create an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBMediation"}],"url":"\/documentation\/chartboostsdk\/chbmediation"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostAdSessionContext":{"role":"symbol","title":"OMIDChartboostAdSessionContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostAdSessionContext"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdSessionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostAdSessionContext"}],"url":"\/documentation\/chartboostsdk\/omidchartboostadsessioncontext"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostAdSession":{"role":"symbol","title":"OMIDChartboostAdSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostAdSession"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostAdSession"}],"url":"\/documentation\/chartboostsdk\/omidchartboostadsession"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost":{"role":"symbol","title":"Chartboost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"}],"abstract":[{"type":"text","text":"Provides global settings and shared functionality for the Chartboost SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chartboost"}],"url":"\/documentation\/chartboostsdk\/chartboost"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostSDK":{"role":"symbol","title":"OMIDChartboostSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostSDK"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostSDK"}],"url":"\/documentation\/chartboostsdk\/omidchartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAd":{"role":"symbol","title":"CHBAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAd"}],"abstract":[{"type":"text","text":"The protocol to which all Chartboost ads conform to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAd"}],"url":"\/documentation\/chartboostsdk\/chbad"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDCreativeType":{"role":"symbol","title":"OMIDCreativeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDCreativeType"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDCreativeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeType"}],"url":"\/documentation\/chartboostsdk\/omidcreativetype"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDImpressionType":{"role":"symbol","title":"OMIDImpressionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDImpressionType"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDImpressionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionType"}],"url":"\/documentation\/chartboostsdk\/omidimpressiontype"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerSizeMedium":{"role":"symbol","title":"CHBBannerSizeMedium","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSizeMedium"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"}],"abstract":[{"type":"text","text":"“Medium Rect” - Medium banner size on phones."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeMedium","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerSizeMedium"}],"url":"\/documentation\/chartboostsdk\/chbbannersizemedium"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDOwner":{"role":"symbol","title":"OMIDOwner","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDOwner"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDOwner"}],"url":"\/documentation\/chartboostsdk\/omidowner"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDPlayerState":{"role":"symbol","title":"OMIDPlayerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDPlayerState"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDPlayerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerState"}],"url":"\/documentation\/chartboostsdk\/omidplayerstate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode":{"role":"symbol","title":"CacheErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed cache operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheErrorCode"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate":{"role":"symbol","title":"CHBAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"}],"abstract":[{"type":"text","text":"The protocol which all Chartboost ad delegates inherit from."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitialDelegate":{"role":"symbol","title":"CHBInterstitialDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitialDelegate"}],"abstract":[{"type":"text","text":"Interstitial delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitialDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBInterstitialDelegate"}],"url":"\/documentation\/chartboostsdk\/chbinterstitialdelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerSize":{"role":"symbol","title":"CHBBannerSize","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSize"}],"abstract":[{"type":"text","text":"Defines standard sizes for CHBBanner objects."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerSize"}],"url":"\/documentation\/chartboostsdk\/chbbannersize"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewardedDelegate":{"role":"symbol","title":"CHBRewardedDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewardedDelegate"}],"abstract":[{"type":"text","text":"Rewarded delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewardedDelegate"}],"url":"\/documentation\/chartboostsdk\/chbrewardeddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostVerificationScriptResource":{"role":"symbol","title":"OMIDChartboostVerificationScriptResource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostVerificationScriptResource"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostVerificationScriptResource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostVerificationScriptResource"}],"url":"\/documentation\/chartboostsdk\/omidchartboostverificationscriptresource"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode":{"role":"symbol","title":"ShowErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed show operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorCode"}],"url":"\/documentation\/chartboostsdk\/showerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError":{"role":"symbol","title":"CacheError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheError"}],"abstract":[{"type":"text","text":"An error object passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheError"}],"url":"\/documentation\/chartboostsdk\/cacheerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewardEvent":{"role":"symbol","title":"CHBRewardEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewardEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on reward-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewardEvent"}],"url":"\/documentation\/chartboostsdk\/chbrewardevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewarded":{"role":"symbol","title":"CHBRewarded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewarded"}],"abstract":[{"type":"text","text":"CHBRewarded is a full-screen ad that provides some reward to the user."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewarded"}],"url":"\/documentation\/chartboostsdk\/chbrewarded"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostPartner":{"role":"symbol","title":"OMIDChartboostPartner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostPartner"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostPartner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostPartner"}],"url":"\/documentation\/chartboostsdk\/omidchartboostpartner"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial":{"role":"symbol","title":"CHBInterstitial","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitial"}],"abstract":[{"type":"text","text":"CHBInterstitial is a full-screen ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBInterstitial"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDInteractionType":{"role":"symbol","title":"OMIDInteractionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDInteractionType"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDInteractionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionType"}],"url":"\/documentation\/chartboostsdk\/omidinteractiontype"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostAdEvents":{"role":"symbol","title":"OMIDChartboostAdEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostAdEvents"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostAdEvents"}],"url":"\/documentation\/chartboostsdk\/omidchartboostadevents"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ChartboostVersionString":{"role":"symbol","title":"ChartboostVersionString","fragments":[{"kind":"identifier","text":"ChartboostVersionString"}],"abstract":[{"type":"text","text":"Project version string for Chartboost."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ChartboostVersionString","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/chartboostversionstring"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/RedirectionURLFinished":{"role":"symbol","title":"RedirectionURLFinished","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RedirectionURLFinished"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/RedirectionURLFinished","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RedirectionURLFinished"}],"url":"\/documentation\/chartboostsdk\/redirectionurlfinished"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDismissEvent":{"role":"symbol","title":"CHBDismissEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDismissEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on dismiss-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDismissEvent"}],"url":"\/documentation\/chartboostsdk\/chbdismissevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode":{"role":"symbol","title":"StartErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed start operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartErrorCode"}],"url":"\/documentation\/chartboostsdk\/starterrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBClickEvent":{"role":"symbol","title":"CHBClickEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBClickEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickEvent"}],"url":"\/documentation\/chartboostsdk\/chbclickevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerSizeLeaderboard":{"role":"symbol","title":"CHBBannerSizeLeaderboard","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSizeLeaderboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"}],"abstract":[{"type":"text","text":"“Tablet” - Leaderboard banner size on tablets."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeLeaderboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerSizeLeaderboard"}],"url":"\/documentation\/chartboostsdk\/chbbannersizeleaderboard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostScriptInjector":{"role":"symbol","title":"OMIDChartboostScriptInjector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostScriptInjector"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostScriptInjector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostScriptInjector"}],"url":"\/documentation\/chartboostsdk\/omidchartboostscriptinjector"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickError":{"role":"symbol","title":"ClickError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickError"}],"abstract":[{"type":"text","text":"An error object passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickError"}],"url":"\/documentation\/chartboostsdk\/clickerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostAdSessionConfiguration":{"role":"symbol","title":"OMIDChartboostAdSessionConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostAdSessionConfiguration"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostAdSessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostAdSessionConfiguration"}],"url":"\/documentation\/chartboostsdk\/omidchartboostadsessionconfiguration"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ChartboostVersionNumber":{"role":"symbol","title":"ChartboostVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChartboostVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Project version number for Chartboost."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ChartboostVersionNumber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChartboostVersionNumber"}],"url":"\/documentation\/chartboostsdk\/chartboostversionnumber"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerDelegate":{"role":"symbol","title":"CHBBannerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerDelegate"}],"abstract":[{"type":"text","text":"Banner delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerDelegate"}],"url":"\/documentation\/chartboostsdk\/chbbannerdelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDismissableAdDelegate":{"role":"symbol","title":"CHBDismissableAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDismissableAdDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for ads that can be dismissed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDismissableAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbdismissableaddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBShowEvent":{"role":"symbol","title":"CHBShowEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBShowEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on show-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowEvent"}],"url":"\/documentation\/chartboostsdk\/chbshowevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerSizeStandard":{"role":"symbol","title":"CHBBannerSizeStandard","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSizeStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"}],"abstract":[{"type":"text","text":"“Banner” - Standard banner size on phones."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerSizeStandard"}],"url":"\/documentation\/chartboostsdk\/chbbannersizestandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode":{"role":"symbol","title":"ClickErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed click operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickErrorCode"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdEvent":{"role":"symbol","title":"CHBAdEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdEvent"}],"abstract":[{"type":"text","text":"CHBAdEvent is a NSObject subclass, it contains information about a specific event and is related to an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdEvent"}],"url":"\/documentation\/chartboostsdk\/chbadevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard":{"role":"symbol","title":"CHBPrivacyStandard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"abstract":[{"type":"text","text":"Constant that identifies a privacy standard to comply to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandard"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/OMIDChartboostMediaEvents":{"role":"symbol","title":"OMIDChartboostMediaEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDChartboostMediaEvents"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/OMIDChartboostMediaEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDChartboostMediaEvents"}],"url":"\/documentation\/chartboostsdk\/omidchartboostmediaevents"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBImpressionEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError"]},{"title":"Protocols","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitialDelegate","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate"]},{"title":"Variables","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeLeaderboard","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeMedium","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSizeStandard","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ChartboostVersionNumber","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ChartboostVersionString"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard"]},{"title":"Enumerations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartError\/title","value":"CHBStartError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartError\/fragments","value":[{"kind":"identifier","text":"CHBStartError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/title","value":"CHBBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/fragments","value":[{"kind":"identifier","text":"CHBBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel\/title","value":"CBLoggingLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBImpressionEvent\/title","value":"CHBImpressionEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBImpressionEvent\/fragments","value":[{"kind":"identifier","text":"CHBImpressionEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowError\/title","value":"CHBShowError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowError\/fragments","value":[{"kind":"identifier","text":"CHBShowError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/title","value":"CHBCacheEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/fragments","value":[{"kind":"identifier","text":"CHBCacheEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation\/title","value":"CHBMediation"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation\/fragments","value":[{"kind":"identifier","text":"CHBMediation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/title","value":"Chartboost"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/fragments","value":[{"kind":"identifier","text":"Chartboost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/title","value":"CHBAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/fragments","value":[{"kind":"identifier","text":"CHBAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeMedium\/title","value":"CHBBannerSizeMedium"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeMedium\/fragments","value":[{"kind":"identifier","text":"CHBBannerSizeMedium"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/title","value":"CHBCacheErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/title","value":"CHBAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitialDelegate\/title","value":"CHBInterstitialDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitialDelegate\/fragments","value":[{"kind":"identifier","text":"CHBInterstitialDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSize\/title","value":"CHBBannerSize"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSize\/fragments","value":[{"kind":"identifier","text":"CHBBannerSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/title","value":"CHBRewardedDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/fragments","value":[{"kind":"identifier","text":"CHBRewardedDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/title","value":"CHBShowErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/title","value":"CHBCacheError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/fragments","value":[{"kind":"identifier","text":"CHBCacheError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardEvent\/title","value":"CHBRewardEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardEvent\/fragments","value":[{"kind":"identifier","text":"CHBRewardEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/title","value":"CHBRewarded"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/fragments","value":[{"kind":"identifier","text":"CHBRewarded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial\/title","value":"CHBInterstitial"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial\/fragments","value":[{"kind":"identifier","text":"CHBInterstitial"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissEvent\/title","value":"CHBDismissEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissEvent\/fragments","value":[{"kind":"identifier","text":"CHBDismissEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/title","value":"CHBStartErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/title","value":"CHBClickEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/fragments","value":[{"kind":"identifier","text":"CHBClickEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeLeaderboard\/title","value":"CHBBannerSizeLeaderboard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeLeaderboard\/fragments","value":[{"kind":"identifier","text":"CHBBannerSizeLeaderboard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/title","value":"CHBClickError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/fragments","value":[{"kind":"identifier","text":"CHBClickError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ChartboostVersionNumber\/title","value":"ChartboostVersionNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ChartboostVersionNumber\/fragments","value":[{"kind":"identifier","text":"ChartboostVersionNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/title","value":"CHBBannerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/fragments","value":[{"kind":"identifier","text":"CHBBannerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate\/title","value":"CHBDismissableAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBDismissableAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBShowEvent\/title","value":"CHBShowEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBShowEvent\/fragments","value":[{"kind":"identifier","text":"CHBShowEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeStandard\/title","value":"CHBBannerSizeStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSizeStandard\/fragments","value":[{"kind":"identifier","text":"CHBBannerSizeStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/title","value":"CHBClickErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent\/title","value":"CHBAdEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdEvent\/fragments","value":[{"kind":"identifier","text":"CHBAdEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/title","value":"CHBPrivacyStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandard"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}