{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClickAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent","text":"CHBClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError","text":"ClickError"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A click event with info related to the ad clicked."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error specifying the failure reason, or nil if the operation was successful."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement to be notified of when an ad has been clicked."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the click does not result into the opening of a link an error will be provided explaning why."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A typical implementation would look like this:"}]},{"type":"codeListing","syntax":"objc","code":["- (void)didClickAd:(CHBClickEvent *)event error:(nullable CHBClickError *)error {","   if (error) {","       \/\/ Handle error","   } else {","       \/\/ Maybe pause ongoing processes like video or gameplay when a banner ad is clicked.","   }","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbaddelegate\/didclickad(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbaddelegate\/didclickad(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didClickAd(_:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called after an ad has been clicked."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didClickAd:error:"}],"role":"symbol","title":"didClickAd(_:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClickAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)CHBAdDelegate(im)didClickAd:error:","required":true,"modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate":{"role":"symbol","title":"CHBAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"}],"abstract":[{"type":"text","text":"The protocol which all Chartboost ad delegates inherit from."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/didClickAd(_:error:)":{"navigatorTitle":[{"kind":"identifier","text":"didClickAd:error:"}],"role":"symbol","title":"didClickAd(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didClickAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called after an ad has been clicked."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didClickAd(_:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostsdk\/chbaddelegate\/didclickad(_:error:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickError":{"role":"symbol","title":"ClickError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickError"}],"abstract":[{"type":"text","text":"An error object passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickError"}],"url":"\/documentation\/chartboostsdk\/clickerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBClickEvent":{"role":"symbol","title":"CHBClickEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBClickEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickEvent"}],"url":"\/documentation\/chartboostsdk\/chbclickevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didClickAd:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didClickAd:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didClickAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent","text":"CHBClickEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError","text":"CHBClickError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/title","value":"CHBAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didClickAd(_:error:)\/title","value":"didClickAd:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didClickAd(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didClickAd:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/title","value":"CHBClickError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/fragments","value":[{"kind":"identifier","text":"CHBClickError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/title","value":"CHBClickEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/fragments","value":[{"kind":"identifier","text":"CHBClickEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}