{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCacheAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","preciseIdentifier":"c:objc(cs)CHBCacheEvent","text":"CHBCacheEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBCacheError","text":"CacheError"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A cache event with info related to the cached ad."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error specifying the failure reason, or nil if the operation was successful."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement to be notified of when an ad is ready to be shown after the cache method has been called."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A typical implementation would look like this:"}]},{"type":"codeListing","syntax":"objc","code":["- (void)didCacheAd:(CHBCacheEvent *)event error:(nullable CHBCacheError *)error {","   if (error) {","       \/\/ Handle error","   } else {","       \/\/ At this point event.ad.isCached will be true, and the ad is ready to be shown.","   }","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbaddelegate\/didcachead(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbaddelegate\/didcachead(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didCacheAd(_:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called after a cache call, either if an ad has been loaded from the Chartboost servers and cached, or tried to but failed."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didCacheAd:error:"}],"role":"symbol","title":"didCacheAd(_:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCacheAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBCacheEvent","preciseIdentifier":"c:objc(cs)CHBCacheEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBCacheError"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)CHBAdDelegate(im)didCacheAd:error:","required":true,"modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate":{"role":"symbol","title":"CHBAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"}],"abstract":[{"type":"text","text":"The protocol which all Chartboost ad delegates inherit from."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBCacheEvent":{"role":"symbol","title":"CHBCacheEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCacheEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheEvent"}],"url":"\/documentation\/chartboostsdk\/chbcacheevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheError":{"role":"symbol","title":"CacheError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheError"}],"abstract":[{"type":"text","text":"An error object passed on cache-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheError"}],"url":"\/documentation\/chartboostsdk\/cacheerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/didCacheAd(_:error:)":{"navigatorTitle":[{"kind":"identifier","text":"didCacheAd:error:"}],"role":"symbol","title":"didCacheAd(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCacheAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBCacheEvent","preciseIdentifier":"c:objc(cs)CHBCacheEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CacheError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBCacheError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called after a cache call, either if an ad has been loaded from the Chartboost servers and cached, or tried to but failed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didCacheAd(_:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostsdk\/chbaddelegate\/didcachead(_:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didCacheAd:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCacheAd:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didCacheAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBCacheEvent","preciseIdentifier":"c:objc(cs)CHBCacheEvent","text":"CHBCacheEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBCacheError","text":"CHBCacheError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/title","value":"CHBAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/title","value":"CHBCacheEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBCacheEvent\/fragments","value":[{"kind":"identifier","text":"CHBCacheEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/title","value":"CHBCacheError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheError\/fragments","value":[{"kind":"identifier","text":"CHBCacheError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didCacheAd(_:error:)\/title","value":"didCacheAd:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didCacheAd(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCacheAd:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}