{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didShowAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent","preciseIdentifier":"c:objc(cs)CHBShowEvent","text":"CHBShowEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBShowError","text":"ShowError"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A show event with info related to the ad shown."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error specifying the failure reason, or nil if the operation was successful."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement to be notified of when the ad presentation process has finished."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method will be called once for each call to showFromViewController: on an interstitial or rewarded ad."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In contrast, this may be called up to two times after showing a banner, if some error occurs after the ad has been successfully shown."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A common practice consists of caching an ad here so there’s an ad ready for the next time you need to show it."}]},{"type":"codeListing","syntax":"objc","code":["- (void)didShowAd:(CHBShowEvent *)event error:(nullable CHBShowError *)error {","   if (error) {","       \/\/ Handle error, possibly resuming processes paused in willShowAd:","   } else {","       [event.ad cache];","   }","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbaddelegate\/didshowad(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbaddelegate\/didshowad(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didShowAd(_:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called after a showFromViewController: call, either if the ad has been presented and an ad impression logged, or if the operation failed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didShowAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBShowEvent","preciseIdentifier":"c:objc(cs)CHBShowEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShowError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBShowError"},{"kind":"text","text":"?)"}],"title":"didShowAd(_:error:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)CHBAdDelegate(im)didShowAd:error:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didShowAd:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBShowEvent":{"role":"symbol","title":"CHBShowEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBShowEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on show-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowEvent"}],"url":"\/documentation\/chartboostsdk\/chbshowevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate":{"role":"symbol","title":"CHBAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAdDelegate"}],"abstract":[{"type":"text","text":"The protocol which all Chartboost ad delegates inherit from."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAdDelegate/didShowAd(_:error:)":{"role":"symbol","title":"didShowAd(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didShowAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBShowEvent","preciseIdentifier":"c:objc(cs)CHBShowEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShowError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBShowError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called after a showFromViewController: call, either if the ad has been presented and an ad impression logged, or if the operation failed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAdDelegate\/didShowAd(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didShowAd:error:"}],"url":"\/documentation\/chartboostsdk\/chbaddelegate\/didshowad(_:error:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowError":{"role":"symbol","title":"ShowError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowError"}],"abstract":[{"type":"text","text":"An error object passed on show-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowError"}],"url":"\/documentation\/chartboostsdk\/showerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didShowAd:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didShowAd:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didShowAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBShowEvent","preciseIdentifier":"c:objc(cs)CHBShowEvent","text":"CHBShowEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBShowError","text":"CHBShowError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBShowEvent\/title","value":"CHBShowEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBShowEvent\/fragments","value":[{"kind":"identifier","text":"CHBShowEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/title","value":"CHBAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didShowAd(_:error:)\/title","value":"didShowAd:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAdDelegate~1didShowAd(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didShowAd:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowError\/title","value":"CHBShowError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowError\/fragments","value":[{"kind":"identifier","text":"CHBShowError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}