{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Consent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH","doc:\/\/com.chartboost.ChartboostSDK\/SY","doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Consent options for GDPR compliance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Consent"}],"title":"CHBDataUseConsent.GDPR.Consent","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@CHBGDPRConsent","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Consent"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/behavioral","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/nonBehavioral"]},{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/Equatable-Implementations","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/Consent-swift.enum/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum\/rawrepresentable-implementations"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR":{"role":"symbol","title":"CHBDataUseConsent.GDPR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPR"}],"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with GDPR."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GDPR"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/Consent-swift.enum/nonBehavioral":{"role":"symbol","title":"CHBDataUseConsent.GDPR.Consent.nonBehavioral","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonBehavioral"}],"abstract":[{"type":"text","text":"User does not consent to behavioral targeting in compliance with GDPR."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/nonBehavioral","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBGDPRConsentNonBehavioral"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum\/nonbehavioral"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/Consent-swift.enum/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum\/init(rawvalue:)"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/Consent-swift.enum/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum\/equatable-implementations"},"doc://com.chartboost.ChartboostSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s8SendableP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/Consent-swift.enum":{"role":"symbol","title":"CHBDataUseConsent.GDPR.Consent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Consent"}],"abstract":[{"type":"text","text":"Consent options for GDPR compliance."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Consent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SY"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/Consent-swift.enum/behavioral":{"role":"symbol","title":"CHBDataUseConsent.GDPR.Consent.behavioral","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"behavioral"}],"abstract":[{"type":"text","text":"User consents to behavioral targeting in compliance with GDPR."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/behavioral","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBGDPRConsentBehavioral"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum\/behavioral"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CHBGDPRConsent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBGDPRConsent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBGDPRConsent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/behavioral","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum\/nonBehavioral"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBGDPRConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR\/title","value":"CHBGDPRDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR\/fragments","value":[{"kind":"identifier","text":"CHBGDPRDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum~1nonBehavioral\/title","value":"CHBGDPRConsentNonBehavioral"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum~1nonBehavioral\/fragments","value":[{"kind":"identifier","text":"CHBGDPRConsentNonBehavioral"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum\/title","value":"CHBGDPRConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum\/fragments","value":[{"kind":"identifier","text":"CHBGDPRConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum~1behavioral\/title","value":"CHBGDPRConsentBehavioral"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum~1behavioral\/fragments","value":[{"kind":"identifier","text":"CHBGDPRConsentBehavioral"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}