{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent","text":"CHBDataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR","preciseIdentifier":"c:objc(cs)CHBGDPRDataUseConsent","text":"GDPR"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum","preciseIdentifier":"c:@E@CHBGDPRConsent","text":"Consent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"consent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The desired GDPR consent option."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/init(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/init(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/init(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a GDPR consent object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GDPR","preciseIdentifier":"c:objc(cs)CHBGDPRDataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Consent","preciseIdentifier":"c:@E@CHBGDPRConsent"},{"kind":"text","text":")"}],"title":"init(_:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)CHBGDPRDataUseConsent(cm)gdprConsent:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"gdprConsent:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GDPR","preciseIdentifier":"c:objc(cs)CHBGDPRDataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Consent","preciseIdentifier":"c:@E@CHBGDPRConsent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a GDPR consent object."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/init(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gdprConsent:"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/init(_:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR":{"role":"symbol","title":"CHBDataUseConsent.GDPR","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPR"}],"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with GDPR."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GDPR"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/GDPR/Consent-swift.enum":{"role":"symbol","title":"CHBDataUseConsent.GDPR.Consent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Consent"}],"abstract":[{"type":"text","text":"Consent options for GDPR compliance."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Consent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/gdpr\/consent-swift.enum"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"gdprConsent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"gdprConsent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR","preciseIdentifier":"c:objc(cs)CHBGDPRDataUseConsent","text":"CHBGDPRDataUseConsent"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"gdprConsent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/GDPR\/Consent-swift.enum","preciseIdentifier":"c:@E@CHBGDPRConsent","text":"CHBGDPRConsent"},{"kind":"text","text":")"},{"kind":"internalParam","text":"consent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1init(_:)\/title","value":"gdprConsent:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1init(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"gdprConsent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR\/title","value":"CHBGDPRDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR\/fragments","value":[{"kind":"identifier","text":"CHBGDPRDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum\/title","value":"CHBGDPRConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1GDPR~1Consent-swift.enum\/fragments","value":[{"kind":"identifier","text":"CHBGDPRConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}