{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBShowErrorCode","text":"ShowErrorCode"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/showerror\/showcode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError\/showCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShowErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBShowErrorCode"},{"kind":"text","text":"?"}],"title":"showCode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChartboostSDK9ShowErrorC8showCodeAA0cdF0OSgvp","modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowError":{"role":"symbol","title":"ShowError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowError"}],"abstract":[{"type":"text","text":"An error object passed on show-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowError"}],"url":"\/documentation\/chartboostsdk\/showerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode":{"role":"symbol","title":"ShowErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed show operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorCode"}],"url":"\/documentation\/chartboostsdk\/showerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowError/showCode":{"role":"symbol","title":"showCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ShowErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBShowErrorCode"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowError\/showCode","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/showerror\/showcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowError\/title","value":"CHBShowError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowError\/fragments","value":[{"kind":"identifier","text":"CHBShowError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/title","value":"CHBShowErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}