{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataUseConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent","text":"CHBDataUseConsent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method can be called multiple times to set the consent for different privacy standards."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If a consent has already been set for a privacy standard, adding a consent object for that standard will overwrite the previous value."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method should be called before starting the Chartboost SDK with startWithAppID:appSignature:completion: if possible."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The added consents are persisted, so you may just call this when the consent status needs to be updated."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chartboost\/adddatauseconsent(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chartboost\/adddatauseconsent(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/addDataUseConsent(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use to restrict Chartboost’s ability to collect personal data from the user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataUseConsent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":")"}],"title":"addDataUseConsent(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)Chartboost(cm)addDataUseConsent:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addDataUseConsent:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost":{"role":"symbol","title":"Chartboost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"}],"abstract":[{"type":"text","text":"Provides global settings and shared functionality for the Chartboost SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chartboost"}],"url":"\/documentation\/chartboostsdk\/chartboost"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/addDataUseConsent(_:)":{"role":"symbol","title":"addDataUseConsent(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addDataUseConsent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use to restrict Chartboost’s ability to collect personal data from the user."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/addDataUseConsent(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addDataUseConsent:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/adddatauseconsent(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"addDataUseConsent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addDataUseConsent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addDataUseConsent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent","text":"CHBDataUseConsent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"consent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/title","value":"Chartboost"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/fragments","value":[{"kind":"identifier","text":"Chartboost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1addDataUseConsent(_:)\/title","value":"addDataUseConsent:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1addDataUseConsent(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"addDataUseConsent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}