{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataUseConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"privacyStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard","text":"CHBPrivacyStandard"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent","text":"CHBDataUseConsent"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A CHBDataUseConsent subclass (the same one used to set the consent in addDataUseConsent:) or nil if no consent status is currently available."}]}]},{"kind":"parameters","parameters":[{"name":"privacyStandard","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The privacy standard for which you want to obtain the consent status."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this to check the current consent status, either set by a call to addDataUseConsent: or persisted from a call to the same method on a previous app run. You may need to cast the returned object to the proper CHBDataUseConsent subclass in order to read its consent value."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, to check if a consent is not set for GDPR:"}]},{"type":"codeListing","syntax":"objc","code":["\/\/ Obj-C","if (![Chartboost dataUseConsentForPrivacyStandard:CHBPrivacyStandardGDPR]) { ... }","\/\/ Swift","if Chartboost.dataUseConsent(for: .GDPR) == nil { ... }"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To check the specific consent status for GDPR:"}]},{"type":"codeListing","syntax":"objc","code":["\/\/ Obj-C","CHBGDPRDataUseConsent *gdpr = [Chartboost dataUseConsentForPrivacyStandard:CHBPrivacyStandardGDPR];","if (gdpr && gdpr.consent == CHBGDPRConsentNonBehavioral) { ... }","\/\/ Swift","let gdpr = Chartboost.dataUseConsent(for: .GDPR) as? CHBDataUseConsent.GDPR","if gdpr?.consent == .nonBehavioral { ... }"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chartboost\/datauseconsent(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chartboost\/datauseconsent(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/dataUseConsent(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the current consent status for the desired privacy standard."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataUseConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":"?"}],"title":"dataUseConsent(for:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)Chartboost(cm)dataUseConsentForPrivacyStandard:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"dataUseConsentForPrivacyStandard:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost":{"role":"symbol","title":"Chartboost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"}],"abstract":[{"type":"text","text":"Provides global settings and shared functionality for the Chartboost SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chartboost"}],"url":"\/documentation\/chartboostsdk\/chartboost"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard":{"role":"symbol","title":"CHBPrivacyStandard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"abstract":[{"type":"text","text":"Constant that identifies a privacy standard to comply to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandard"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/dataUseConsent(for:)":{"role":"symbol","title":"dataUseConsent(for:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataUseConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the current consent status for the desired privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/dataUseConsent(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataUseConsentForPrivacyStandard:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/datauseconsent(for:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"dataUseConsentForPrivacyStandard:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"dataUseConsentForPrivacyStandard:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"__kindof CHBDataUseConsent","preciseIdentifier":"c:Q$objc(cs)CHBDataUseConsent"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"dataUseConsentForPrivacyStandard:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"privacyStandard"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/title","value":"Chartboost"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/fragments","value":[{"kind":"identifier","text":"Chartboost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/title","value":"CHBPrivacyStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1dataUseConsent(for:)\/title","value":"dataUseConsentForPrivacyStandard:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1dataUseConsent(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"dataUseConsentForPrivacyStandard:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}