{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"appID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBStartError","text":"StartError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"appID","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Chartboost application ID for this app."}]}]},{"name":"appSignature","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Chartboost application signature for this app."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A completion block to be executed when the SDK finishes initializing."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It takes an error parameter which indicates if the initialization succeeded or not."},{"type":"text","text":" "},{"type":"text","text":"This method must be called before creating an ad. Other methods, like data use consent or logging level methods, are fine to call before start."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chartboost\/start(withappid:appsignature:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chartboost\/start(withappid:appsignature:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/start(withAppID:appSignature:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Starts the SDK with the publisher app credentials."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StartError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBStartError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"start(withAppID:appSignature:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)Chartboost(cm)startWithAppID:appSignature:completion:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"startWithAppID:appSignature:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost":{"role":"symbol","title":"Chartboost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chartboost"}],"abstract":[{"type":"text","text":"Provides global settings and shared functionality for the Chartboost SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chartboost"}],"url":"\/documentation\/chartboostsdk\/chartboost"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/Chartboost/start(withAppID:appSignature:completion:)":{"role":"symbol","title":"start(withAppID:appSignature:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"appSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StartError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBStartError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Starts the SDK with the publisher app credentials."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/Chartboost\/start(withAppID:appSignature:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithAppID:appSignature:completion:"}],"url":"\/documentation\/chartboostsdk\/chartboost\/start(withappid:appsignature:completion:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartError":{"role":"symbol","title":"StartError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartError"}],"abstract":[{"type":"text","text":"An error object passed on SDK start completion callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartError"}],"url":"\/documentation\/chartboostsdk\/starterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"startWithAppID:appSignature:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppID:appSignature:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWithAppID:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"appID"},{"kind":"text","text":" "},{"kind":"identifier","text":"appSignature:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"appSignature"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(CHBStartError *)","preciseIdentifier":"c:BFv(#*$@M@ChartboostSDK@objc(cs)CHBStartError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/title","value":"Chartboost"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost\/fragments","value":[{"kind":"identifier","text":"Chartboost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1start(withAppID:appSignature:completion:)\/title","value":"startWithAppID:appSignature:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1Chartboost~1start(withAppID:appSignature:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithAppID:appSignature:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartError\/title","value":"CHBStartError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartError\/fragments","value":[{"kind":"identifier","text":"CHBStartError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}