{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard","text":"CHBPrivacyStandard"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbprivacystandard\/ccpa"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbprivacystandard\/ccpa"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/CCPA","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"title":"CCPA","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@CHBPrivacyStandardCCPA","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandardCCPA"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard":{"role":"symbol","title":"CHBPrivacyStandard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"abstract":[{"type":"text","text":"Constant that identifies a privacy standard to comply to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandard"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard/CCPA":{"role":"symbol","title":"CCPA","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard\/CCPA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandardCCPA"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard\/ccpa"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"CHBPrivacyStandardCCPA"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandardCCPA"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"CHBPrivacyStandardCCPA"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/title","value":"CHBPrivacyStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1CCPA\/title","value":"CHBPrivacyStandardCCPA"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard~1CCPA\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandardCCPA"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}