{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBClickErrorCode","text":"ClickErrorCode"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/clickerror\/clickcode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError\/clickCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClickErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBClickErrorCode"},{"kind":"text","text":"?"}],"title":"clickCode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13ChartboostSDK10ClickErrorC9clickCodeAA0cdF0OSgvp","modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode":{"role":"symbol","title":"ClickErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed click operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickErrorCode"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickError":{"role":"symbol","title":"ClickError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickError"}],"abstract":[{"type":"text","text":"An error object passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickError"}],"url":"\/documentation\/chartboostsdk\/clickerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickError/clickCode":{"role":"symbol","title":"clickCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClickErrorCode","preciseIdentifier":"c:@M@ChartboostSDK@E@CHBClickErrorCode"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error code that indicates the failure reason."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError\/clickCode","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk\/clickerror\/clickcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/title","value":"CHBClickErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/title","value":"CHBClickError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/fragments","value":[{"kind":"identifier","text":"CHBClickError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}