{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/cblogginglevel\/verbose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/cblogginglevel\/verbose"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/verbose","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"title":"CBLoggingLevel.verbose","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CBLoggingLevel@CBLoggingLevelVerbose","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevelVerbose"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel":{"role":"symbol","title":"CBLoggingLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBLoggingLevel"}],"abstract":[{"type":"text","text":"Chartboost SDK logging level options"}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevel"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CBLoggingLevel/verbose":{"role":"symbol","title":"CBLoggingLevel.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CBLoggingLevel\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CBLoggingLevelVerbose"}],"url":"\/documentation\/chartboostsdk\/cblogginglevel\/verbose"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CBLoggingLevelVerbose"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevelVerbose"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CBLoggingLevelVerbose"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel\/title","value":"CBLoggingLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1verbose\/title","value":"CBLoggingLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CBLoggingLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"CBLoggingLevelVerbose"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}