{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriInvalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/clickerrorcode\/uriinvalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/clickerrorcode\/uriinvalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriInvalid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriInvalid"}],"title":"ClickErrorCode.uriInvalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostSDK@E@CHBClickErrorCode@CHBClickErrorCodeUriInvalid","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBClickErrorCodeUriInvalid"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/uriInvalid":{"role":"symbol","title":"ClickErrorCode.uriInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriInvalid"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriInvalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickErrorCodeUriInvalid"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode\/uriinvalid"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode":{"role":"symbol","title":"ClickErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed click operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickErrorCode"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CHBClickErrorCodeUriInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCodeUriInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBClickErrorCodeUriInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriInvalid\/title","value":"CHBClickErrorCodeUriInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriInvalid\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCodeUriInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/title","value":"CHBClickErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}