{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriUnrecognized"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/clickerrorcode\/uriunrecognized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/clickerrorcode\/uriunrecognized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriUnrecognized","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriUnrecognized"}],"title":"ClickErrorCode.uriUnrecognized","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostSDK@E@CHBClickErrorCode@CHBClickErrorCodeUriUnrecognized","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBClickErrorCodeUriUnrecognized"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode/uriUnrecognized":{"role":"symbol","title":"ClickErrorCode.uriUnrecognized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uriUnrecognized"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode\/uriUnrecognized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickErrorCodeUriUnrecognized"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode\/uriunrecognized"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickErrorCode":{"role":"symbol","title":"ClickErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed click operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickErrorCode"}],"url":"\/documentation\/chartboostsdk\/clickerrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CHBClickErrorCodeUriUnrecognized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCodeUriUnrecognized"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBClickErrorCodeUriUnrecognized"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriUnrecognized\/title","value":"CHBClickErrorCodeUriUnrecognized"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode~1uriUnrecognized\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCodeUriUnrecognized"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/title","value":"CHBClickErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBClickErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}