{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/cacheerrorcode\/internetunavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/cacheerrorcode\/internetunavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internetUnavailable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"title":"CacheErrorCode.internetUnavailable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostSDK@E@CHBCacheErrorCode@CHBCacheErrorCodeInternetUnavailable","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeInternetUnavailable"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode":{"role":"symbol","title":"CacheErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed cache operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheErrorCode"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/internetUnavailable":{"role":"symbol","title":"CacheErrorCode.internetUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/internetUnavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeInternetUnavailable"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/internetunavailable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CHBCacheErrorCodeInternetUnavailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeInternetUnavailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBCacheErrorCodeInternetUnavailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/title","value":"CHBCacheErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1internetUnavailable\/title","value":"CHBCacheErrorCodeInternetUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1internetUnavailable\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeInternetUnavailable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}