{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noAdFound"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/cacheerrorcode\/noadfound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/cacheerrorcode\/noadfound"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/noAdFound","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noAdFound"}],"title":"CacheErrorCode.noAdFound","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostSDK@E@CHBCacheErrorCode@CHBCacheErrorCodeNoAdFound","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeNoAdFound"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode/noAdFound":{"role":"symbol","title":"CacheErrorCode.noAdFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noAdFound"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode\/noAdFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCacheErrorCodeNoAdFound"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode\/noadfound"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CacheErrorCode":{"role":"symbol","title":"CacheErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed cache operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CacheErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CacheErrorCode"}],"url":"\/documentation\/chartboostsdk\/cacheerrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CHBCacheErrorCodeNoAdFound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeNoAdFound"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBCacheErrorCodeNoAdFound"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1noAdFound\/title","value":"CHBCacheErrorCodeNoAdFound"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode~1noAdFound\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCodeNoAdFound"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/title","value":"CHBCacheErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CacheErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBCacheErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}