{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkFailure"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/starterrorcode\/networkfailure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/starterrorcode\/networkfailure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/networkFailure","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkFailure"}],"title":"StartErrorCode.networkFailure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostSDK@E@CHBStartErrorCode@CHBStartErrorCodeNetworkFailure","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBStartErrorCodeNetworkFailure"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode":{"role":"symbol","title":"StartErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed start operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartErrorCode"}],"url":"\/documentation\/chartboostsdk\/starterrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/StartErrorCode/networkFailure":{"role":"symbol","title":"StartErrorCode.networkFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkFailure"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/StartErrorCode\/networkFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBStartErrorCodeNetworkFailure"}],"url":"\/documentation\/chartboostsdk\/starterrorcode\/networkfailure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CHBStartErrorCodeNetworkFailure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCodeNetworkFailure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBStartErrorCodeNetworkFailure"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/title","value":"CHBStartErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1networkFailure\/title","value":"CHBStartErrorCodeNetworkFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1StartErrorCode~1networkFailure\/fragments","value":[{"kind":"identifier","text":"CHBStartErrorCodeNetworkFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}