{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismissAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","preciseIdentifier":"c:objc(cs)CHBDismissEvent","text":"CHBDismissEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dismiss event with info related to the dismissed ad."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement to be notified of when an ad is no longer displayed."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that this method won’t get called for ads that failed to be shown. To handle that case implement didShowAd:error:"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You may use the error property inside the event to know if the dismissal was expected or caused by an error."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A typical implementation would look like this:"}]},{"type":"codeListing","syntax":"objc","code":["- (void)didDismissAd:(CHBDismissEvent *)event {","   \/\/ Resume processes paused in willShowAd:","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdismissableaddelegate\/diddismissad(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdismissableaddelegate\/diddismissad(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate\/didDismissAd(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called after an ad is dismissed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismissAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDismissEvent","preciseIdentifier":"c:objc(cs)CHBDismissEvent"},{"kind":"text","text":")"}],"title":"didDismissAd(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)CHBDismissableAdDelegate(im)didDismissAd:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didDismissAd:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDismissEvent":{"role":"symbol","title":"CHBDismissEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDismissEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on dismiss-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDismissEvent"}],"url":"\/documentation\/chartboostsdk\/chbdismissevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDismissableAdDelegate/didDismissAd(_:)":{"role":"symbol","title":"didDismissAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismissAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDismissEvent","preciseIdentifier":"c:objc(cs)CHBDismissEvent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called after an ad is dismissed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate\/didDismissAd(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didDismissAd:"}],"url":"\/documentation\/chartboostsdk\/chbdismissableaddelegate\/diddismissad(_:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDismissableAdDelegate":{"role":"symbol","title":"CHBDismissableAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDismissableAdDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol for ads that can be dismissed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissableAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDismissableAdDelegate"}],"url":"\/documentation\/chartboostsdk\/chbdismissableaddelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didDismissAd:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissAd:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didDismissAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDismissEvent","preciseIdentifier":"c:objc(cs)CHBDismissEvent","text":"CHBDismissEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissEvent\/title","value":"CHBDismissEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissEvent\/fragments","value":[{"kind":"identifier","text":"CHBDismissEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate~1didDismissAd(_:)\/title","value":"didDismissAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate~1didDismissAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissAd:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate\/title","value":"CHBDismissableAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDismissableAdDelegate\/fragments","value":[{"kind":"identifier","text":"CHBDismissableAdDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}