{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with CCPA."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"}],"title":"CHBDataUseConsent.CCPA","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)CHBCCPADataUseConsent","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CCPA"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/init(_:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/consent-swift.property"]},{"title":"Enumerations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/Consent-swift.enum"]}],"references":{"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/CCPA/consent-swift.property":{"role":"symbol","title":"consent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CCPA","preciseIdentifier":"c:objc(cs)CHBCCPADataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Consent","preciseIdentifier":"c:@E@CHBCCPAConsent"}],"abstract":[{"type":"text","text":"The CCPA consent option."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/consent-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"consent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa\/consent-swift.property"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/CCPA/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CCPA","preciseIdentifier":"c:objc(cs)CHBCCPADataUseConsent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Consent","preciseIdentifier":"c:@E@CHBCCPAConsent"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a CCPA consent object."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/init(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ccpaConsent:"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa\/init(_:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/CCPA":{"role":"symbol","title":"CHBDataUseConsent.CCPA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"}],"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with CCPA."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CCPA"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/CCPA/Consent-swift.enum":{"role":"symbol","title":"CHBDataUseConsent.CCPA.Consent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Consent"}],"abstract":[{"type":"text","text":"Consent options for CCPA compliance."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/Consent-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Consent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa\/consent-swift.enum"},"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CHBCCPADataUseConsent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCCPADataUseConsent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBCCPADataUseConsent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/consent-swift.property"]},{"title":"Type Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/init(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/Consent-swift.enum"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCCPADataUseConsent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent","text":"CHBDataUseConsent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1consent-swift.property\/title","value":"consent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1consent-swift.property\/fragments","value":[{"kind":"identifier","text":"consent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1init(_:)\/title","value":"ccpaConsent:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1init(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"ccpaConsent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA\/title","value":"CHBCCPADataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA\/fragments","value":[{"kind":"identifier","text":"CHBCCPADataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1Consent-swift.enum\/title","value":"CHBCCPAConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1Consent-swift.enum\/fragments","value":[{"kind":"identifier","text":"CHBCCPAConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}