{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"COPPA"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject","doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP","doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP","doc:\/\/com.chartboost.ChartboostSDK\/SQ","doc:\/\/com.chartboost.ChartboostSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with COPPA."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"COPPA"}],"title":"CHBDataUseConsent.COPPA","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)CHBCOPPADataUseConsent","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"COPPA"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/init(isChildDirected:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/isChildDirected"]}],"references":{"doc://com.chartboost.ChartboostSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SQ"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/COPPA/isChildDirected":{"role":"symbol","title":"isChildDirected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChildDirected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates if the app is directed to children."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/isChildDirected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isChildDirected"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa\/ischilddirected"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/COPPA":{"role":"symbol","title":"CHBDataUseConsent.COPPA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"COPPA"}],"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with COPPA."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"COPPA"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/SH"},"doc://com.chartboost.ChartboostSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s28CustomDebugStringConvertibleP"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/COPPA/init(isChildDirected:)":{"role":"symbol","title":"init(isChildDirected:)","fragments":[{"kind":"text","text":"\/*not inherited*\/ "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isChildDirected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a COPPA consent object."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/init(isChildDirected:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isChildDirected:"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa\/init(ischilddirected:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s7CVarArgP"},"doc://com.chartboost.ChartboostSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/objc(pl)NSObject"},"doc://com.chartboost.ChartboostSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CHBCOPPADataUseConsent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCOPPADataUseConsent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CHBCOPPADataUseConsent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/isChildDirected"]},{"title":"Type Methods","identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/init(isChildDirected:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBCOPPADataUseConsent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","preciseIdentifier":"c:objc(cs)CHBDataUseConsent","text":"CHBDataUseConsent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA~1isChildDirected\/title","value":"isChildDirected"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA~1isChildDirected\/fragments","value":[{"kind":"identifier","text":"isChildDirected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA\/title","value":"CHBCOPPADataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA\/fragments","value":[{"kind":"identifier","text":"CHBCOPPADataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA~1init(isChildDirected:)\/title","value":"isChildDirected:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA~1init(isChildDirected:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isChildDirected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}