{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"privacyStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard","text":"CHBPrivacyStandard"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/privacystandard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/privacystandard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/privacyStandard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The identifier for the privacy standard this consent applies to."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"privacyStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"title":"privacyStandard","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)CHBDataUseConsent(py)privacyStandard","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"privacyStandard"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/privacyStandard":{"role":"symbol","title":"privacyStandard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"privacyStandard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBPrivacyStandard","preciseIdentifier":"c:CHBDataUseConsent.h@T@CHBPrivacyStandard"}],"abstract":[{"type":"text","text":"The identifier for the privacy standard this consent applies to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/privacyStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"privacyStandard"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/privacystandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBPrivacyStandard":{"role":"symbol","title":"CHBPrivacyStandard","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBPrivacyStandard"}],"abstract":[{"type":"text","text":"Constant that identifies a privacy standard to comply to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBPrivacyStandard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBPrivacyStandard"}],"url":"\/documentation\/chartboostsdk\/chbprivacystandard"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"privacyStandard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"privacyStandard"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"privacyStandard"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1privacyStandard\/title","value":"privacyStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1privacyStandard\/fragments","value":[{"kind":"identifier","text":"privacyStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/title","value":"CHBPrivacyStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBPrivacyStandard\/fragments","value":[{"kind":"identifier","text":"CHBPrivacyStandard"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}