{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This will do nothing if there’s no cached ad. Otherwise it will remove any data related to the ad,"},{"type":"text","text":" "},{"type":"text","text":"bringing the ad instance back to a non-cached state."},{"type":"text","text":" "},{"type":"text","text":"After calling this method you may call "},{"type":"codeVoice","code":"cache"},{"type":"text","text":" again and a new ad will be fetched."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbrewarded\/clearcache()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbrewarded\/clearcache()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded\/clearCache()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Clears the ad cache."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"title":"clearCache()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)CHBRewarded(im)clearCache","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"clearCache"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewarded/clearCache()":{"role":"symbol","title":"clearCache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clears the ad cache."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded\/clearCache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"url":"\/documentation\/chartboostsdk\/chbrewarded\/clearcache()"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewarded":{"role":"symbol","title":"CHBRewarded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewarded"}],"abstract":[{"type":"text","text":"CHBRewarded is a full-screen ad that provides some reward to the user."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewarded"}],"url":"\/documentation\/chartboostsdk\/chbrewarded"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCache"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded~1clearCache()\/title","value":"clearCache"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded~1clearCache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/title","value":"CHBRewarded"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/fragments","value":[{"kind":"identifier","text":"CHBRewarded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}