{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate","preciseIdentifier":"c:objc(pl)CHBRewardedDelegate","text":"CHBRewardedDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See CHBAdDelegate.h for more info."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbrewarded\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbrewarded\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The delegate instance to receive rewarded callbacks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBRewardedDelegate","preciseIdentifier":"c:objc(pl)CHBRewardedDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)CHBRewarded(py)delegate","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewarded/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBRewardedDelegate","preciseIdentifier":"c:objc(pl)CHBRewardedDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate instance to receive rewarded callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/chartboostsdk\/chbrewarded\/delegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewarded":{"role":"symbol","title":"CHBRewarded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewarded"}],"abstract":[{"type":"text","text":"CHBRewarded is a full-screen ad that provides some reward to the user."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewarded"}],"url":"\/documentation\/chartboostsdk\/chbrewarded"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewardedDelegate":{"role":"symbol","title":"CHBRewardedDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewardedDelegate"}],"abstract":[{"type":"text","text":"Rewarded delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewardedDelegate"}],"url":"\/documentation\/chartboostsdk\/chbrewardeddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<CHBRewardedDelegate>","preciseIdentifier":"c:Qoobjc(pl)CHBRewardedDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/title","value":"CHBRewarded"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/fragments","value":[{"kind":"identifier","text":"CHBRewarded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/title","value":"CHBRewardedDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/fragments","value":[{"kind":"identifier","text":"CHBRewardedDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}