{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate","preciseIdentifier":"c:objc(pl)CHBRewardedDelegate","text":"CHBRewardedDelegate"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Location for the rewarded ad. See the location property documentation."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate for the rewarded ad. See the delegate property documentation."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbrewarded\/init(location:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbrewarded\/init(location:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded\/init(location:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The initializer for the rewarded ad object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBRewardedDelegate","preciseIdentifier":"c:objc(pl)CHBRewardedDelegate"},{"kind":"text","text":"?)"}],"title":"init(location:delegate:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)CHBRewarded(im)initWithLocation:delegate:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLocation:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewardedDelegate":{"role":"symbol","title":"CHBRewardedDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewardedDelegate"}],"abstract":[{"type":"text","text":"Rewarded delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewardedDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewardedDelegate"}],"url":"\/documentation\/chartboostsdk\/chbrewardeddelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewarded/init(location:delegate:)":{"role":"symbol","title":"init(location:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBRewardedDelegate","preciseIdentifier":"c:objc(pl)CHBRewardedDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The initializer for the rewarded ad object."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded\/init(location:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLocation:delegate:"}],"url":"\/documentation\/chartboostsdk\/chbrewarded\/init(location:delegate:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBRewarded":{"role":"symbol","title":"CHBRewarded","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBRewarded"}],"abstract":[{"type":"text","text":"CHBRewarded is a full-screen ad that provides some reward to the user."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBRewarded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBRewarded"}],"url":"\/documentation\/chartboostsdk\/chbrewarded"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLocation:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocation:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLocation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"location"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<CHBRewardedDelegate>","preciseIdentifier":"c:Qoobjc(pl)CHBRewardedDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/title","value":"CHBRewardedDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewardedDelegate\/fragments","value":[{"kind":"identifier","text":"CHBRewardedDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded~1init(location:delegate:)\/title","value":"initWithLocation:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded~1init(location:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLocation:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/title","value":"CHBRewarded"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBRewarded\/fragments","value":[{"kind":"identifier","text":"CHBRewarded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}