{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitialDelegate","preciseIdentifier":"c:objc(pl)CHBInterstitialDelegate","text":"CHBInterstitialDelegate"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See CHBAdDelegate.h for more info."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbinterstitial\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbinterstitial\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The delegate instance to receive interstitial callbacks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBInterstitialDelegate","preciseIdentifier":"c:objc(pl)CHBInterstitialDelegate"},{"kind":"text","text":"?"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)CHBInterstitial(py)delegate","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitialDelegate":{"role":"symbol","title":"CHBInterstitialDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitialDelegate"}],"abstract":[{"type":"text","text":"Interstitial delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitialDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBInterstitialDelegate"}],"url":"\/documentation\/chartboostsdk\/chbinterstitialdelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial":{"role":"symbol","title":"CHBInterstitial","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBInterstitial"}],"abstract":[{"type":"text","text":"CHBInterstitial is a full-screen ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBInterstitial"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBInterstitial/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBInterstitialDelegate","preciseIdentifier":"c:objc(pl)CHBInterstitialDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate instance to receive interstitial callbacks."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBInterstitial\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/chartboostsdk\/chbinterstitial\/delegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<CHBInterstitialDelegate>","preciseIdentifier":"c:Qoobjc(pl)CHBInterstitialDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitialDelegate\/title","value":"CHBInterstitialDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitialDelegate\/fragments","value":[{"kind":"identifier","text":"CHBInterstitialDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial\/title","value":"CHBInterstitial"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial\/fragments","value":[{"kind":"identifier","text":"CHBInterstitial"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBInterstitial~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}