{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method will first check if there is a cached ad and, if found, will do nothing."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If no cached ad exists the method will attempt to fetch it from the Chartboost server."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement didCacheAd:error: in your ad delegate to be notified of a cache request result."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbad\/cache()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbad\/cache()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd\/cache()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Caches an ad."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cache"}],"role":"symbol","title":"cache()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)CHBAd(im)cache","required":true,"modules":[{"name":"ChartboostSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAd/cache()":{"navigatorTitle":[{"kind":"identifier","text":"cache"}],"role":"symbol","title":"cache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Caches an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd\/cache()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostsdk\/chbad\/cache()"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAd":{"role":"symbol","title":"CHBAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAd"}],"abstract":[{"type":"text","text":"The protocol to which all Chartboost ads conform to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAd"}],"url":"\/documentation\/chartboostsdk\/chbad"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cache"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cache"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd~1cache()\/title","value":"cache"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd~1cache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/title","value":"CHBAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/fragments","value":[{"kind":"identifier","text":"CHBAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}