{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller to present the ad on."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method will first check if there is a cached ad, if found it will present it."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Passing a non-nil view controller is required."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbad\/show(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbad\/show(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd\/show(from:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows an ad."}],"kind":"symbol","metadata":{"modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"showFromViewController:"}],"role":"symbol","title":"show(from:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)CHBAd(im)showFromViewController:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"2.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAd/show(from:)":{"navigatorTitle":[{"kind":"identifier","text":"showFromViewController:"}],"role":"symbol","title":"show(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd\/show(from:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/chartboostsdk\/chbad\/show(from:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBAd":{"role":"symbol","title":"CHBAd","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBAd"}],"abstract":[{"type":"text","text":"The protocol to which all Chartboost ads conform to."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBAd"}],"url":"\/documentation\/chartboostsdk\/chbad"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showFromViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showFromViewController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showFromViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd~1show(from:)\/title","value":"showFromViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd~1show(from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showFromViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/title","value":"CHBAd"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBAd\/fragments","value":[{"kind":"identifier","text":"CHBAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}