{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optOutSale"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa\/consent-swift.enum\/optoutsale"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa\/consent-swift.enum\/optoutsale"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/Consent-swift.enum\/optOutSale","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User does not consent to the sale of his or her personal information in compliance with CCPA."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optOutSale"}],"title":"CHBDataUseConsent.CCPA.Consent.optOutSale","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@CHBCCPAConsent@CHBCCPAConsentOptOutSale","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBCCPAConsentOptOutSale"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/Consent-swift.enum"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/CCPA/Consent-swift.enum":{"role":"symbol","title":"CHBDataUseConsent.CCPA.Consent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Consent"}],"abstract":[{"type":"text","text":"Consent options for CCPA compliance."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/Consent-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Consent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa\/consent-swift.enum"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/CCPA/Consent-swift.enum/optOutSale":{"role":"symbol","title":"CHBDataUseConsent.CCPA.Consent.optOutSale","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optOutSale"}],"abstract":[{"type":"text","text":"User does not consent to the sale of his or her personal information in compliance with CCPA."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA\/Consent-swift.enum\/optOutSale","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBCCPAConsentOptOutSale"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa\/consent-swift.enum\/optoutsale"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/CCPA":{"role":"symbol","title":"CHBDataUseConsent.CCPA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CCPA"}],"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with CCPA."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/CCPA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CCPA"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/ccpa"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CHBCCPAConsentOptOutSale"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBCCPAConsentOptOutSale"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBCCPAConsentOptOutSale"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1Consent-swift.enum\/title","value":"CHBCCPAConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1Consent-swift.enum\/fragments","value":[{"kind":"identifier","text":"CHBCCPAConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1Consent-swift.enum~1optOutSale\/title","value":"CHBCCPAConsentOptOutSale"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA~1Consent-swift.enum~1optOutSale\/fragments","value":[{"kind":"identifier","text":"CHBCCPAConsentOptOutSale"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA\/title","value":"CHBCCPADataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1CCPA\/fragments","value":[{"kind":"identifier","text":"CHBCCPADataUseConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}