{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/showerrorcode\/internetunavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/showerrorcode\/internetunavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internetUnavailable","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"title":"ShowErrorCode.internetUnavailable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChartboostSDK@E@CHBShowErrorCode@CHBShowErrorCodeInternetUnavailable","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeInternetUnavailable"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode/internetUnavailable":{"role":"symbol","title":"ShowErrorCode.internetUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetUnavailable"}],"abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode\/internetUnavailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBShowErrorCodeInternetUnavailable"}],"url":"\/documentation\/chartboostsdk\/showerrorcode\/internetunavailable"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ShowErrorCode":{"role":"symbol","title":"ShowErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShowErrorCode"}],"abstract":[{"type":"text","text":"Error codes for failed show operations."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ShowErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ShowErrorCode"}],"url":"\/documentation\/chartboostsdk\/showerrorcode"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CHBShowErrorCodeInternetUnavailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeInternetUnavailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CHBShowErrorCodeInternetUnavailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1internetUnavailable\/title","value":"CHBShowErrorCodeInternetUnavailable"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode~1internetUnavailable\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCodeInternetUnavailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/title","value":"CHBShowErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ShowErrorCode\/fragments","value":[{"kind":"identifier","text":"CHBShowErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}