{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraryVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adapterVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the mediation library used. E.g. “Helium”"}]}]},{"name":"libraryVersion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string representing the library version. E.g. “5.1.0”"}]}]},{"name":"adapterVersion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string representing the Chartbooost adapter version for this library. E.g. “5.1.0.1”"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbmediation\/init(name:libraryversion:adapterversion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbmediation\/init(name:libraryversion:adapterversion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation\/init(name:libraryVersion:adapterVersion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The initializer for the mediation object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraryVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adapterVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(name:libraryVersion:adapterVersion:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)CHBMediation(im)initWithName:libraryVersion:adapterVersion:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithName:libraryVersion:adapterVersion:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBMediation/init(name:libraryVersion:adapterVersion:)":{"role":"symbol","title":"init(name:libraryVersion:adapterVersion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraryVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adapterVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The initializer for the mediation object."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation\/init(name:libraryVersion:adapterVersion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:libraryVersion:adapterVersion:"}],"url":"\/documentation\/chartboostsdk\/chbmediation\/init(name:libraryversion:adapterversion:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBMediation":{"role":"symbol","title":"CHBMediation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBMediation"}],"abstract":[{"type":"text","text":"A class that holds information about the mediation library used to create an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBMediation"}],"url":"\/documentation\/chartboostsdk\/chbmediation"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithName:libraryVersion:adapterVersion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:libraryVersion:adapterVersion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraryVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"libraryVersion"},{"kind":"text","text":" "},{"kind":"identifier","text":"adapterVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"adapterVersion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation~1init(name:libraryVersion:adapterVersion:)\/title","value":"initWithName:libraryVersion:adapterVersion:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation~1init(name:libraryVersion:adapterVersion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:libraryVersion:adapterVersion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation\/title","value":"CHBMediation"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation\/fragments","value":[{"kind":"identifier","text":"CHBMediation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}