{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishHandlingClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent","text":"CHBClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError","text":"ClickError"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A click event with info related to the ad clicked."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error specifying the failure reason, or nil if the operation was successful."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement to be notified of when an ad click has been handled."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This can mean an in-app web browser or App Store app sheet has been dismissed, or that the user came back to the app after the link was opened on an external application."}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A typical implementation would look like this:"}]},{"type":"codeListing","syntax":"objc","code":["- (void)didFinishHandlingClick:(CHBClickEvent *)event error:(nullable CHBClickError *)error {","   \/\/ Resume processes previously paused on didClickAd:error: implementation.","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbbannerdelegate\/didfinishhandlingclick(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbbannerdelegate\/didfinishhandlingclick(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate\/didFinishHandlingClick(_:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the link viewer presented as result of an ad click has been dismissed."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didFinishHandlingClick:error:"}],"role":"symbol","title":"didFinishHandlingClick(_:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishHandlingClick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)CHBBannerDelegate(im)didFinishHandlingClick:error:","modules":[{"name":"ChartboostSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will be removed with the next major update"}]}],"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/ClickError":{"role":"symbol","title":"ClickError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClickError"}],"abstract":[{"type":"text","text":"An error object passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClickError"}],"url":"\/documentation\/chartboostsdk\/clickerror"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerDelegate":{"role":"symbol","title":"CHBBannerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerDelegate"}],"abstract":[{"type":"text","text":"Banner delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerDelegate"}],"url":"\/documentation\/chartboostsdk\/chbbannerdelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerDelegate/didFinishHandlingClick(_:error:)":{"deprecated":true,"role":"symbol","title":"didFinishHandlingClick(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishHandlingClick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when the link viewer presented as result of an ad click has been dismissed."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate\/didFinishHandlingClick(_:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didFinishHandlingClick:error:"}],"url":"\/documentation\/chartboostsdk\/chbbannerdelegate\/didfinishhandlingclick(_:error:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBClickEvent":{"role":"symbol","title":"CHBClickEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBClickEvent"}],"abstract":[{"type":"text","text":"A CHBAdEvent subclass passed on click-related delegate methods."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBClickEvent"}],"url":"\/documentation\/chartboostsdk\/chbclickevent"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didFinishHandlingClick:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishHandlingClick:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didFinishHandlingClick:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBClickEvent","preciseIdentifier":"c:objc(cs)CHBClickEvent","text":"CHBClickEvent"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"event"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/ClickError","preciseIdentifier":"c:@M@ChartboostSDK@objc(cs)CHBClickError","text":"CHBClickError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/title","value":"CHBClickError"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1ClickError\/fragments","value":[{"kind":"identifier","text":"CHBClickError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/title","value":"CHBBannerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/fragments","value":[{"kind":"identifier","text":"CHBBannerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate~1didFinishHandlingClick(_:error:)\/title","value":"didFinishHandlingClick:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate~1didFinishHandlingClick(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didFinishHandlingClick:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/title","value":"CHBClickEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBClickEvent\/fragments","value":[{"kind":"identifier","text":"CHBClickEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}