{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method will first check if there is a cached ad and, if found, will do nothing."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If no cached ad exists the method will attempt to fetch it from the Chartboost server."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement didCacheAd:error: in your ad delegate to be notified of a cache request result."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbbanner\/cache()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbbanner\/cache()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Caches an ad."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"title":"cache()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)CHBBanner(im)cache","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cache"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/cache()":{"role":"symbol","title":"cache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Caches an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/cache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cache"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/cache()"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner":{"role":"symbol","title":"CHBBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"}],"abstract":[{"type":"text","text":"CHBBanner is a UIView subclass able to show banner ads. Once obtained via the provided initializer, the"},{"type":"text","text":" "},{"type":"text","text":"developer is responsible of adding it to the app’s view hierarchy and laying it out properly."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBanner"}],"url":"\/documentation\/chartboostsdk\/chbbanner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cache"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cache"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1cache()\/title","value":"cache"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1cache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/title","value":"CHBBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/fragments","value":[{"kind":"identifier","text":"CHBBanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}