{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize","text":"CHBBannerSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation","preciseIdentifier":"c:objc(cs)CHBMediation","text":"CHBMediation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","preciseIdentifier":"c:objc(pl)CHBBannerDelegate","text":"CHBBannerDelegate"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"size","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Size for the banner. See the size property documentation."}]}]},{"name":"location","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Location for the banner ad. See the location property documentation."}]}]},{"name":"mediation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Information about the mediation SDK that is requesting this ad."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate for the banner ad. See the delegate property documentation."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this initializer only if you are writing an adapter to use Chartboost with another mediation solution."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbbanner\/init(size:location:mediation:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbbanner\/init(size:location:mediation:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:mediation:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The initializer for banner ads intended to be mediated by another SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBMediation","preciseIdentifier":"c:objc(cs)CHBMediation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerDelegate","preciseIdentifier":"c:objc(pl)CHBBannerDelegate"},{"kind":"text","text":"?)"}],"title":"init(size:location:mediation:delegate:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)CHBBanner(im)initWithSize:location:mediation:delegate:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSize:location:mediation:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner":{"role":"symbol","title":"CHBBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"}],"abstract":[{"type":"text","text":"CHBBanner is a UIView subclass able to show banner ads. Once obtained via the provided initializer, the"},{"type":"text","text":" "},{"type":"text","text":"developer is responsible of adding it to the app’s view hierarchy and laying it out properly."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBanner"}],"url":"\/documentation\/chartboostsdk\/chbbanner"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerSize":{"role":"symbol","title":"CHBBannerSize","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerSize"}],"abstract":[{"type":"text","text":"Defines standard sizes for CHBBanner objects."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerSize"}],"url":"\/documentation\/chartboostsdk\/chbbannersize"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBannerDelegate":{"role":"symbol","title":"CHBBannerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBannerDelegate"}],"abstract":[{"type":"text","text":"Banner delegate protocol."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBannerDelegate"}],"url":"\/documentation\/chartboostsdk\/chbbannerdelegate"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBMediation":{"role":"symbol","title":"CHBMediation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBMediation"}],"abstract":[{"type":"text","text":"A class that holds information about the mediation library used to create an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBMediation"}],"url":"\/documentation\/chartboostsdk\/chbmediation"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/init(size:location:mediation:delegate:)":{"role":"symbol","title":"init(size:location:mediation:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBMediation","preciseIdentifier":"c:objc(cs)CHBMediation"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CHBBannerDelegate","preciseIdentifier":"c:objc(pl)CHBBannerDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The initializer for banner ads intended to be mediated by another SDK."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/init(size:location:mediation:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSize:location:mediation:delegate:"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/init(size:location:mediation:delegate:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSize:location:mediation:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSize:location:mediation:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBannerSize","preciseIdentifier":"c:CHBBanner.h@T@CHBBannerSize","text":"CHBBannerSize"},{"kind":"text","text":")"},{"kind":"internalParam","text":"size"},{"kind":"text","text":" "},{"kind":"identifier","text":"location:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"location"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBMediation","preciseIdentifier":"c:objc(cs)CHBMediation","text":"CHBMediation"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mediation"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<CHBBannerDelegate>","preciseIdentifier":"c:Qoobjc(pl)CHBBannerDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/title","value":"CHBBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/fragments","value":[{"kind":"identifier","text":"CHBBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSize\/title","value":"CHBBannerSize"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerSize\/fragments","value":[{"kind":"identifier","text":"CHBBannerSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/title","value":"CHBBannerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBannerDelegate\/fragments","value":[{"kind":"identifier","text":"CHBBannerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation\/title","value":"CHBMediation"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBMediation\/fragments","value":[{"kind":"identifier","text":"CHBMediation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1init(size:location:mediation:delegate:)\/title","value":"initWithSize:location:mediation:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1init(size:location:mediation:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSize:location:mediation:delegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}