{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The view controller to present the ad on."}]}]}]},{"kind":"content","content":[{"anchor":"Discussion","level":1,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method will first check if there is a cached ad, if found it will present it."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If no cached ad exists the method will attempt to fetch it from the Chartboost server first."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Passing a non-nil view controller is required."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement "},{"type":"codeVoice","code":"(didShowAd:error:)"},{"type":"text","text":" in your ad delegate to be notified of a show request result, and "},{"type":"codeVoice","code":"(didCacheAd:error:)"},{"type":"text","text":"  to be notified of the result of a cache request triggered by showing a non-cached banner."}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbbanner\/show(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbbanner\/show(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/show(from:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Shows an ad."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"title":"show(from:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)CHBBanner(im)showFromViewController:","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"showFromViewController:"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner/show(from:)":{"role":"symbol","title":"show(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"show"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Shows an ad."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner\/show(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showFromViewController:"}],"url":"\/documentation\/chartboostsdk\/chbbanner\/show(from:)"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBBanner":{"role":"symbol","title":"CHBBanner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBBanner"}],"abstract":[{"type":"text","text":"CHBBanner is a UIView subclass able to show banner ads. Once obtained via the provided initializer, the"},{"type":"text","text":" "},{"type":"text","text":"developer is responsible of adding it to the app’s view hierarchy and laying it out properly."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBBanner"}],"url":"\/documentation\/chartboostsdk\/chbbanner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showFromViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showFromViewController:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showFromViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1show(from:)\/title","value":"showFromViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner~1show(from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showFromViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/title","value":"CHBBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBBanner\/fragments","value":[{"kind":"identifier","text":"CHBBanner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}