{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChildDirected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa\/ischilddirected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa\/ischilddirected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/isChildDirected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates if the app is directed to children."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChildDirected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isChildDirected","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)CHBCOPPADataUseConsent(py)isChildDirected","modules":[{"name":"ChartboostSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isChildDirected"}]},"hierarchy":{"paths":[["doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA"]]},"references":{"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK":{"role":"collection","title":"ChartboostSDK","abstract":[],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK","kind":"symbol","type":"topic","url":"\/documentation\/chartboostsdk"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/COPPA/isChildDirected":{"role":"symbol","title":"isChildDirected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChildDirected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates if the app is directed to children."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA\/isChildDirected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isChildDirected"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa\/ischilddirected"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent/COPPA":{"role":"symbol","title":"CHBDataUseConsent.COPPA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"COPPA"}],"abstract":[{"type":"text","text":"CHBDataUseConsent subclass for compliance with COPPA."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent\/COPPA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"COPPA"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent\/coppa"},"doc://com.chartboost.ChartboostSDK/documentation/ChartboostSDK/CHBDataUseConsent":{"role":"symbol","title":"CHBDataUseConsent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CHBDataUseConsent"}],"abstract":[{"type":"text","text":"Abstract class. Subclasses define a data use consent option for a privacy standard."}],"identifier":"doc:\/\/com.chartboost.ChartboostSDK\/documentation\/ChartboostSDK\/CHBDataUseConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CHBDataUseConsent"}],"url":"\/documentation\/chartboostsdk\/chbdatauseconsent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isChildDirected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isChildDirected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChildDirected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA~1isChildDirected\/title","value":"isChildDirected"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA~1isChildDirected\/fragments","value":[{"kind":"identifier","text":"isChildDirected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA\/title","value":"CHBCOPPADataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent~1COPPA\/fragments","value":[{"kind":"identifier","text":"CHBCOPPADataUseConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/title","value":"CHBDataUseConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.chartboost.ChartboostSDK~1documentation~1ChartboostSDK~1CHBDataUseConsent\/fragments","value":[{"kind":"identifier","text":"CHBDataUseConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}